### ISSUE TITLE
Suggestion: use different example for binding rule of dependent pair types

### ISSUE THREAD

**Issue by AxelBoldt** [HoTT/book#1004]
In 1.6, the book says abut dependent pair types: "... automatically scope over the rest of the expression unless delimited, so e.g. ∑(x:A) B(x) × C(x) means ∑(x:A) (B(x) × C(x))." 

This example is not very good for two reasons: the other binding wouldn't make sense in this expression since x appears in both factors, and the general rule "multiplication before summation" suggests anyway that × should bind stronger than ∑ . To tell the novice reader how unusual the binding rule for dependent types really is, I would use   "∑(x:A) B(x) -> C means ∑(x:A) (B(x) -> C)."

**Comment by mikeshulman** [comment]
That seems reasonable to me.
