### ISSUE TITLE
Lebesgue measure in HOTT

### ISSUE THREAD

**Issue by VincentSe** [HoTT/book#1007]
This is more an open question for HOTT than an issue found in the HOTT book.

In section 11.5, compactness of the interval, some things are said about covering subsets of R by families of open intervals. It is also the core of the Lebesgue measure of a subset A : the infimum of the lengths of countable covers of A by open intervals.

The end of the section says "we have provided ample justification for the claim that analysis can be developed in homotopy type theory".

Does this apply to the construction of the Lebesgue measure above (Caratheodory's theorem) ?

The problem is that we need to approximate the infimum at an arbitrary precision : for all epsilon > 0, we need a countable cover by open intervals which length is in [infimum, infimum + epsilon]. This is trivial in classical logic, where any infimum has a sequence that converges to it. But in constructive logic it seems very hard, because subsets of R are very complicated and there is no algorithm to cover them tightly by open intervals.

I guess a section in the HOTT book about measure theory would be nice.

**Comment by mikeshulman** [comment]
I don't expect there are any difficulties in measure theory that are
specific to HoTT, above and beyond those that are intrinsic to any kind of
constructive mathematics (and hence none if you add LEM to HoTT).  So I
don't think it would be a good use of space to spend a long time on measure
theory in the HoTT book.

If you're interested in constructive measure theory, I believe there's a
fair amount of it in Bishop+Bridges.

**Comment by spitters** [comment]
Compactness of the unit interval (Heine-Borel) is indeed important in
constructive measure theory.
However, Bishop has shown how to develop large parts of measure theory
without it.

For an approach to measure theory using synthetic topology and HoTT see:
http://www.cs.au.dk/~spitters/ProbProg.pdf
