### ISSUE TITLE
Switches for changing notation

### ISSUE THREAD

**Issue by Alizter** [HoTT/book#1011]
Sometimes it can be a bit clumsy to write down sigma types (and pi types too), especially if they have large amounts of arguments in the index. Can we have a flag somewhere to change the notation? (Or perhaps an easy way to change it).

So for example `\sm{x:A} B` would write `(x : A) \times B` rather than `\sum_{x:A} B`.

This would allow us to compile the book in agda-style if we wish.

**Comment by mikeshulman** [comment]
The macros are defined in `macros.tex`, anyone who wants to can change them before compiling.

**Comment by andrejbauer** [comment]
I would expect that such a change would incur a lot of editing work. I'd be curious to see someone try, but not me.
