### ISSUE TITLE
Broken link in voe12 reference

### ISSUE THREAD

**Issue by lambda** [HoTT/book#1015]
The following reference contains a broken link, and the source is not archived on Archive.org:

```
@unpublished{Universe-poly,
	Author = {Vladimir Voevodsky},
	Note = {\url{http://uf-ias-2012.wikispaces.com/file/view/Universe+polymorphic+type+sytem.pdf}},
	Title = {A universe polymorphic type system},
Year = 2012}
```

There are a few places where I can find what seems to be the referenced notes, but it is hard to tell what the canonical link should be:

* http://www.math.ias.edu/Voevodsky/files/files-annotated/Dropbox/Unfinished_papers/Dynamic_logic/Stage_9_2012_09_01/Universe%20polymorphic%20type%20sytem.pdf
* https://github.com/UniMath/Universe_Polymorphic_Type_System/blob/master/Universe_polymorphic_type_sytem.pdf

**Comment by mikeshulman** [comment]
Thanks for reporting!  I've submited a PR with what I think is the correct canonical link, at least it's to the "official" archival copy of the wiki that the old broken URL pointed to.
