### ISSUE TITLE
Same letter $P$ is used for different propose in the proof of a lemma

### ISSUE THREAD

**Issue by u5943321** [HoTT/book#1021]
On page 284, lemma 8.6.2, there is a $P$ in the statement of theorem, where $P: A \to B\to (n + m)-Type$. But in the proof, the book defined another $P: A\ to U$. Could you please consider using a different letter such like $Q$? Just a minor suggestion, maybe it is not such elegant to use the same letter to denote different things in the same proof.

**Comment by mikeshulman** [comment]
Yes, you are right, a different letter should be used.  Thanks for the bug report!
