### ISSUE TITLE
Help finding an image

### ISSUE THREAD

**Issue by colasbd** [HoTT/book#1029]
Hi, I'm looking for the image (if possible at a high resolution)

![Capture d’écran 2019-05-22 à 12 29 37](https://user-images.githubusercontent.com/4303814/58167966-782da100-7c8d-11e9-96ed-55b08c58df59.png)

which is a bit different to the one I've found on this repo.

I found this old version more beautiful. I would like to use this picture as an illustration in a document I give to my students about history/philosophy of maths in which I talk about foundations.

Thanks

**Comment by guillaumebrunerie** [comment]
Is this what you are looking for?

https://raw.githubusercontent.com/HoTT/book/d4ad575d266f3060498f2d589fa26dbe8a55d69e/cover.png

**Comment by colasbd** [comment]
Yes exactly!
Thanks a lot
