### ISSUE TITLE
swap parameters for swap function

### ISSUE THREAD

**Issue by luminans** [HoTT/book#1059]
Implicitly, we assume that b:A and a:B in the swap function as in BEFORE.
I think a:A and b:B are more intuitive than b:A and a:B as in AFTER. 

BEFORE:
We can define this by
\[ \mathsf{swap}(A,B,C,g) \defeq \lam{b}{a} g(a)(b). \]
We might also equivalently write the type arguments as subscripts:
\[ \mathsf{swap}_{A,B,C}(g)(b,a) \defeq g(a,b). \]

AFTER
We can define this by
\[ \mathsf{swap}(A,B,C,g) \defeq \lam{a}{b} g(b)(a). \]
We might also equivalently write the type arguments as subscripts:
\[ \mathsf{swap}_{A,B,C}(g)(a,b) \defeq g(b,a). \]

**Comment by mikeshulman** [comment]
No, I think the current version correctly has b:B and a:A.  Given the stated type of swap, the argument g has type A->B->C, while the term specified must have type B->A->C, so \lam{b}{a} g(a)(b) is exactly right.

**Comment by luminans** [comment]
Thanks for your comment. It was not mechanically intuitive although the swap function could be the simplest polymorphic function. 

Thanks for your notes on g. In the context, I got to know that the argument g has type A->B->C, but it is not specified there.

**Comment by mikeshulman** [comment]
It is specified by the type signature of swap, in which the fourth argument has type A->B->C, and g is the fourth argument of swap.
