### ISSUE TITLE
Definition and notation of dependent functions?

### ISSUE THREAD

**Issue by luminans** [HoTT/book#1060]
The elements of a Π-type are functions whose codomain type can vary depending on the element of the domain to which the function is applied, called dependent functions. 

If I read the definition of dependent functions literally, I construct the type of dependent functions $\prd{x:A} ({x} -> B(x)) : \UU$ given a type $A:\UU$ and a family $B:A \to \UU$, where {x} is the singleton type of x. Is $\prd{x:A} B(x)$ a shortened version for notational convenience? Or is the definition above a bit restricted to functions from types?

It bothers me a lot in a sense that I can read the notation a little differently from the definition. I hope it helps to clarify the notational consistency directly from the definition.

**Comment by mikeshulman** [comment]
Where did you get the idea that singleton types are involved?  Singleton types haven't even been defined.

**Comment by luminans** [comment]
I know that I stretched the concept of the singleton set. I don't know how complicated to introduce the singleton type there.

But I see its value in the following discussions. For example, if B is a constant family, then the dependent product type is the ordinary function type. It becomes notationally trivial as a cartesian product over A.

∏(x:A), B ≡ (A → B) is not clear that f(a)≡B or f(a) : B(a). I read f(a)≡B for the first time.

**Comment by mikeshulman** [comment]
Bringing in singletons wouldn't change the constant-family case at all either.  The way the standard notation is, the ∏(x:A), just reduces to A → in the constant-family case.

Of course you can't tell how to read a notation until you've been informed, but the text introducing it explains the meaning.

**Comment by luminans** [comment]
∏(x:A), ( {x} → B ) ≡ (A → B) 
In spite of the constant-family special case, I can see the definition better in the left-hand side that results in the right-hand side.

**Comment by mikeshulman** [comment]
Well, ultimately no one can argue with what seems more intuitive for you, but you'll need to learn the standard notation.  However, I'll try once more and point out that ∏(x:A), ( {x} → B ) looks like a function taking *two* arguments, one in A and one in {x}, when in fact a dependent function takes only one argument.

**Comment by luminans** [comment]
Thanks for your kind comments!
