### ISSUE TITLE
Missing substitution rule?

### ISSUE THREAD

**Issue by mikeshulman** [HoTT/book#1061]
See [this question](https://math.stackexchange.com/q/3752483/91608).  Is A.2 missing a substitution rule?  It shouldn't be depending on A.1.

**Comment by cangiuli** [comment]
This is one of the dozens of congruence rules suppressed in that section. See the discussion at the very end of A.2.2. In this case, it's the principle that Id-formation preserves definitional equality (uisng reflexivity of definitional equality).

Reading the prose there, however, I see that it could be read as "_introduction forms_ preserve definitional equality", but the intent was "_all forms_ preserve definitional equality". Do you think it would help to clarify that sentence (starting "Additionally, for all the type formers below,").

**Comment by cangiuli** [comment]
P.S. Another possibility is that we could remark on even more admissible substitution principles (e.g., substituting equals for a variable yields equals). This might be the best way to avoid future confusion. But I just want to stress that in the way A.2 is set up, this principle is a consequence of the aforementioned suppressed congruence rules.

**Comment by mikeshulman** [comment]
Thanks.  I think it would be clearest for the newcomer if we state this admissible substitution principle alongside the other admissible rules.  We could perhaps remark on how the assumed primitive congruence rules mentioned at the end are what enable us to prove this, since otherwise I expect someone somewhere will think "but why do we need to assume these, since they're special cases of the substitution principle".
