### ISSUE TITLE
Possible Typo in Section 5.3

### ISSUE THREAD

**Issue by joe126333** [HoTT/book#1064]
In Section 5.3, the constructor for a W-type is given as $\Pi_{x :A}$, but shouldn't it be $\Sigma_{x:A}$?  When constructing the natural numbers, it seems to be making use of $\Sigma$ types.  For example, when defining $0$ it appears to be applying the constructor to a pair.

**Comment by mikeshulman** [comment]
The notation $\Pi_{x:A} B(x) \to C(x)$ means $\Pi_{x:A} (B(x) \to C(x))$, which is equivalent to $(\Sigma_{x:A} B(x)) \to C(x)$.  See section 1.4.

**Comment by joe126333** [comment]
> The notation $\Pi_{x:A} B(x) \to C(x)$ means $\Pi_{x:A} (B(x) \to C(x))$, which is equivalent to $(\Sigma_{x:A} B(x)) \to C(x)$. See section 1.4.

**Comment by joe126333** [comment]
That you.  I had forgotten the convention.
