### ISSUE TITLE
Example 9.1.15: every isomorphism is an identity?

### ISSUE THREAD

**Issue by giorgio93p** [HoTT/book#1074]
I have trouble understanding what is meant by 

> If A is a category, then A_0 is a set if and only if for any a, b : A_0 , the type a ≅ b
> is a mere proposition. This is equivalent to saying that every isomorphism in A is an identity;
https://github.com/HoTT/book/blob/a0040d8c075d033f748508b09728fe6869ecc60d/categories.tex#L204

What does it mean for an isomorphism `f : a ≅ b` to _be_ an identity? Of course, it can't be equal to an identity in general, since an identity would have a different type altogether, e.g. `a ≅ a` (and `a`, `b` may not be judgementally equal). However, if we interpret "being an identity" as "being able to be transported to an identity", then this is true for isomorphisms in all categories, by equation (9.1.10) (setting `p` to be `refl_a` and `q` to be `isotoid(f^-1)`).

As an example, consider the discrete category on the interval type. In what sense is `seg` an identity?

**Comment by mikeshulman** [comment]
Maybe it would be better to say "every *automorphism* is an identity".

**Comment by DanGrayson** [comment]
Maybe expand that to "every automorphism is an identity arrow".

**Comment by mikeshulman** [comment]
Sure.
