### ISSUE TITLE
Abbrev used before introduced

### ISSUE THREAD

**Issue by sunziping2016** [HoTT/book#1083]
## Suggested solution

https://github.com/HoTT/book/blob/1ac94087575f3aee19dcecc88ecdea2ba9170ca6/basics.tex#L805

`pr_1` is applied on the identity type instead of product type. Should it be `$\apfunc{\proj1}(\mathsf{lift}(u,p)) = p$`? So are the follows.

https://github.com/HoTT/book/blob/1ac94087575f3aee19dcecc88ecdea2ba9170ca6/basics.tex#L849-L851

## Origin

![image](https://user-images.githubusercontent.com/8998546/126069244-a9fc8a8e-6311-4fde-8371-031a43b4968c.png)

## After change

![image](https://user-images.githubusercontent.com/8998546/126069259-7c864c3d-1369-4f87-bfaf-7708034886f4.png)

**Comment by sunziping2016** [comment]
In section 2.4, it states `f(p)` is the same as `ap_f(p)`. But I think it is confusing to use an abbrev before it is introduced.

**Comment by mikeshulman** [comment]
The abbreviation is introduced in section 2.2, after the proofs of Lemma 2.2.1.

**Comment by sunziping2016** [comment]
> The abbreviation is introduced in section 2.2, after the proofs of Lemma 2.2.1.

Actually, it is introduced here.

https://github.com/HoTT/book/blob/1ac94087575f3aee19dcecc88ecdea2ba9170ca6/basics.tex#L1024

When I continued to read the book, I found it's not a typo but a use before introduction. However, it made me confusing. And I believe someone else may encounter the same problem.

**Comment by DanGrayson** [comment]
Here's what Mike was referring to:

<img width="869" alt="Screen Shot 2021-07-20 at 7 34 19 AM" src="https://user-images.githubusercontent.com/700228/126317368-98b13fc1-ba99-49bc-8c0c-89fb860c7f9b.png">

**Comment by mikeshulman** [comment]
Right.  The line in section 2.4 you point to says "Recall" because it is reminding the reader of a notation that was introduced previously.

**Comment by sunziping2016** [comment]
> Here's what Mike was referring to:
> 
> <img alt="Screen Shot 2021-07-20 at 7 34 19 AM" width="869" src="https://user-images.githubusercontent.com/700228/126317368-98b13fc1-ba99-49bc-8c0c-89fb860c7f9b.png">

Oh, I miss it. Thanks. I'll close the issue.
