### ISSUE TITLE
Typo in §2.9?

### ISSUE THREAD

**Issue by ilhikki** [HoTT/book#1088]
The comma at the end seems to be redundant?
https://github.com/HoTT/book/blob/4101ad33057e57cabbf832359403b19ab71a525a/basics.tex#L1617
![oie_XZWHk7FOYNVg](https://user-images.githubusercontent.com/29532519/135751936-016af1ca-52db-482e-a656-156ac1507d98.png)

**Comment by mikeshulman** [comment]
It's a period, but yes indeed!  Would you like to submit a pull request?
