### ISSUE TITLE
Typo in §2.14

### ISSUE THREAD

**Issue by ilhikki** [HoTT/book#1091]
https://github.com/HoTT/book/blob/3220cfa75a8b5e549dba1928e1142b272fcf1cef/basics.tex#L2208
```latex
In the next two sections, we describe two ways in which univalence makes
it easier to work with such semigroups.
```
The "sections" here seems to be the "subsections".

**Comment by mikeshulman** [comment]
Yes, that would probaby be more correct.  Would you like to submit a pull request?  (No erratum needed, I think.)
