### ISSUE TITLE
Equation equality-semigroup-mult not numbered in subsection 2.14.2

### ISSUE THREAD

**Issue by ilhikki** [HoTT/book#1092]
https://github.com/HoTT/book/blob/3220cfa75a8b5e549dba1928e1142b272fcf1cef/basics.tex#L2322
This equation is referenced but not numbered, so this reference goes to the title of the subsection.
![actual](https://user-images.githubusercontent.com/29532519/140454573-31d310f9-6d5a-4156-a188-6dc2829155b6.jpg)
And what is expected is
![expect](https://user-images.githubusercontent.com/29532519/140454587-a2bbb569-d0dd-4271-b5e6-b3825dfb95eb.jpg)

**Comment by mikeshulman** [comment]
You're right!  Fortunately this is an easy fix, just change `equation*` to `equation`.  And since it's at the end of section 2.14, it won't alter the numbering of anything else.  Would you like to submit a pull request?
