### ISSUE TITLE
parenthesis missing on page 67

### ISSUE THREAD

**Issue by prime235711** [HoTT/book#1100]
I think it should be changed that first projection of coproduct type should be apparently parenthesized.

`\sum_(x:A) P(x) \rightarrow A`

**Comment by mikeshulman** [comment]
Page 67 of which version?

**Comment by Alizter** [comment]
Just before lemma 2.3.2 it seems. I'm still not sure what needs to be changed however.

**Comment by mikeshulman** [comment]
Ah!  I think @prime235711 means it should be `(\sum_(x:A) P(x)) \rightarrow A`, in accord with the rule that sigmas and pis scope over the rest of the expression unless delimited.

**Comment by mikeshulman** [comment]
Would you like to submit a pull request?

**Comment by prime235711** [comment]
I'm new to github, so I don't understand what'd you mean. Can someone please do that for me?

**Comment by shiranaiyo** [comment]
Bumping as I think this issue can be closed now.
