### ISSUE TITLE
Broken links on https://homotopytypetheory.org/book/

### ISSUE THREAD

**Issue by leahneukirchen** [HoTT/book#1105]
Not sure this reaches the right people here, but the PDF links on top of https://homotopytypetheory.org/book/ are broken, and redirect to http://saunders.phil.cmu.edu/book/hott-online.pdf which doesn't exist.

**Comment by mikeshulman** [comment]
Yeah, we've implemented a fix on the repo, but it hasn't made it out to that site yet.  I'll work on it.

**Comment by mikeshulman** [comment]
Done!
