### ISSUE TITLE
What qualifies as a "constructor" and the omitted $\equiv$ rules in appendix A.2

### ISSUE THREAD

**Issue by Ryunaq** [HoTT/book#1113]
Disclaimer: I'm new to type theory.

I'm trying to have a good understanding of the formalism in appendix A.2. The book says the following

> Additionally, for all the type formers below, we assume rules stating that each constructor preserves definitional equality in each of its arguments; for instance, along with the Π-INTRO rule, (Π-INTRO-EQ rule here).

Given the example, I understand that there is a rule X-INTRO-EQ for every type former X. I would understand the same thing applies to make rules X-FORM-EQ. What I'm not sure is if the same applies for rules X-ELIM-EQ, since the eliminations rules do not seem to "construct" but rather eliminate. I've been told they do count, but I wanted to double check and maybe do a pull request specifying that this applies to exactly these 3 types of rules.

This arised when I tried to show that `f \equiv g` implies `f(a) \equiv g(a)` but I got stucked.

**Comment by mikeshulman** [comment]
I think yes, this should apply to X-ELIM-EQ as well.  If so, I think you're right that the word "constructor" is confusing.   I think the intent was that we often view the syntax as inductively generated at the meta-level, and in this case each type- and term-forming rule (including both introductions and eliminations) is a meta-level "constructor" of this inductive type of syntax.  Would it be clearer to say something like "each type- and term-forming operator"?

**Comment by Ryunaq** [comment]
I see, thanks for clearing the use of the word "constructor".  Yes, I think your proposed solution would work fine. Maybe just mention the full list for the Π-Types, to be on the safe side, I'll be making a PR.

**Comment by cangiuli** [comment]
Yes, this applies also to elimination rules; there is a PI-ELIM-EQ.

FWIW I'd say that PI-ELIM "constructs" a term of type B[a/x], but I see how this phrasing is confusing. +1 to Mike's suggestion "each type- and term-forming operator".
