### ISSUE TITLE
Clarification of the proof of Lemma 6.2.9. (universal property of the circle)

### ISSUE THREAD

**Issue by FernandoChu** [HoTT/book#1123]
Here's the proof for easy reference
![image](https://user-images.githubusercontent.com/17756312/177013817-7720daf2-b7f1-41ed-b6be-8d47f28881f5.png)

(In what follows, I've renamed the $f $ in the proof to $\varphi $)

For two fibers $(f  , eqf) ,(g , eqg) : fib_{\varphi} (b , l) $ to be equal, we must show $ p: f = g$, which as mentioned can be proven by the uniqueness principle and functional extensionality, and also that $p_* (eqf) = eqg$. I have not been able to show this, though I've [shown](https://github.com/Ryunaq/HoTT-Book-Agda/blob/main/Chapter6/Book.agda#L119) that it's enough to have `(ap φ p)⁻¹ ∙ eqf  = eqg`.

I'm stuck in this last step, is this what the proof had in mind? or maybe I'm just overcomplicating it.

**Comment by mikeshulman** [comment]
I think you're right, this was the intent (and so the invocation of the uniqueness principle is perhaps overly glib).  I don't know offhand the best way to do this; probably you could deduce it from the construction of `p` in the proof of the uniqueness principle.

**Comment by Ryunaq** [comment]
I've been thinking about this, and doing path induction on `p` and `eqf` in `(ap φ p)⁻¹ ∙ eqf = eqg` simplifies the goal to `refl (φ f) ≡ eqg`, which is false, so while the proof should be able to carried out, I'm suspecting it is not possible to carry it out directly, as was implied. Would you welcome PR using the usual bi-invertible maps?

**Comment by mikeshulman** [comment]
You would only do path induction on p if you were trying to prove that this
equality holds for *all* p, and it makes sense that that wouldn't be true.
I meant that you'd need to use the construction of your *specific* p.

**Comment by shiranaiyo** [comment]
Thanks, you're right. I've been thinking about this. We can not induct on `p` but we can induct on `eqg`, it is also enough to prove it for the case where `f` and `eqf` are the ones from recursion, i.e. `f` is `𝕊¹-rec A b l` and `eqf` is given by pairing `refl b` with the computation principle of `f`. With this assumptions, we need
```
ap φ (funext (𝕊¹-ind-uniq f g (refl b) (𝕊¹-rec-comp A b l))) = eqf
```

Where `𝕊¹-ind-uniq` is the function from Lemma 6.2.8.

This seems true but I see no way to prove this...

**Comment by mikeshulman** [comment]
I think it is much easier to prove that this map has a quasi-inverse, and apply adjointification, than to prove directly that it has contractible fibers.  Having contractible fibers, like being a half-adjoint equivalence, contains an extra coherence 2-path that makes it a proposition, but which is harder to construct in examples, and I think that's what's causing the pain here.

**Comment by shiranaiyo** [comment]
Yup I definetely agree, managing 2-paths is still very hard (to me). I suggest again maybe changing to the usual quasi-inverses proof, I can PR if you want.

**Comment by shiranaiyo** [comment]
I've just finished it! (I've also formalized it in [my agda repo](https://github.com/shiranaiyo/HoTT-Book-Agda/blob/b0a6ea213f29b1b991ccffa9adfcade23eb725a2/src/Chapter6/Book.lagda.md#L122)).

I'll be closing this issue :)

Thank you!
