### ISSUE TITLE
The Cauchy real numbers satisfy the fundamental theorem of algebra and are not Cauchy complete in the rest of the constructive mathematics literature

### ISSUE THREAD

**Issue by MadeleineBirchfield** [HoTT/book#1124]
The term "Cauchy real numbers" is already well defined in the constructive mathematics literature to be equivalence classes of Cauchy sequences of rational numbers (possibly with moduli of convergence), and already proven to satisfy the fundamental theorem of algebra and not be Cauchy complete. See for example, Robert Lubarsky, "[On the Cauchy Completeness of the Constructive Cauchy Reals](https://arxiv.org/abs/1510.00639)", or Wim Ruitenberg, "[Constructing Roots of Polynomials over the Complex Numbers](https://www.mscsnet.mu.edu/~wim/publica/roots_new.pdf)", or Auke Booij, "[Analysis in univalent type theory](https://etheses.bham.ac.uk/id/eprint/10411/7/Booij2020PhD.pdf)"

This book currently attempts to appropriate the already well defined "Cauchy real numbers" to define a new concept in constructive mathematics, "the free Cauchy complete metric space generated by the rationals". This really deserves its own term. Otherwise one risks confusing the reader over what a "Cauchy real number" actually is with the conflicting definitions.

**Comment by mikeshulman** [comment]
FWIW, Lubarsky's paper and Booij's thesis postdate the HoTT Book, so they aren't evidence of anything known "already" from the point of view of the book.  (I looked at Ruitenberg's paper but didn't find either a publication date or a mention of Cauchy completeness of the Cauchy reals.)  But I'm sure it's long been known that the usual proof of Cauchy completeness of the set of equivalence classes of Cauchy sequences requires countable choice, although it looks like Lubarsky may have been the first to construct actual countermodels.

None of that is really relevant to the question of terminology though.  Practically speaking, at this point, approaching 10 years after publication, I don't think the terminology in the book is going to be changed in such a radical way.  Personally, I don't find it out of bounds to propose changing the name of a not-very-useful concept to refer instead to a slight variation thereof that is more useful, especially when the two coincide under a very common assumption (countable choice).  Terminology in mathematics often ebbs and flows in this way over time, as we gradually settle on better and better definitions.

Perhaps @andrejbauer will have some thoughts.

**Comment by nicolaikraus** [comment]
Terminology can't be completely foundation-agnostic. It's a good idea to make it as foundation-agnostic as possible, but with respect to what? Does it have to be the literal concrete definition (a.k.a. implementation), which is what Auke's thesis does? That's a good approach, but I don't think it's the only valid approach. When defining a known concept X in a new foundation/setting, it's reasonable to look at what properties of X are desirable and check whether the new foundation allows a "better" implementation.

The statement in the title of this issue also isn't really correct since there's constructive mathematics literature that assumes CC (countable choice). I don't say this to nit-pick, but I want to challenge the implicit assumption that constructive set theory with [without] CC should correspond to type theory with [without] CC. Type theory has ways to avoid CC that set theory doesn't have, and arguably also has motivations for avoiding CC that set theory doesn't have. Thus, I'm not convinced by an argument of the form "in constructive set theory without CC, X has property P, so it should be the same in HoTT without CC".

**Comment by MadeleineBirchfield** [comment]
@mikeshulman @nicolaikraus The semantic scholar page for Ruitenberg's paper says that it was published in 1990:
https://www.semanticscholar.org/paper/Constructing-roots-of-polynomials-over-the-complex-Ruitenburg/88955bd36b35ab3de1a753782a782ceca58bcd0c
and the paper rejects the use of countable choice in the foundations when proving the fundamental theorem of algebra for the Cauchy reals. 
The fundamental theorem of algebra remains unproven for the "Cauchy reals" that appears in the HoTT book, and it is probably likely that there are foundations where the FTA is false for the HoTT book Cauchy reals where weak countable choice is false.

**Comment by MadeleineBirchfield** [comment]
Another paper in type theory which uses "Cauchy real numbers" to refer to the traditional definition in terms of equivalence classes of Cauchy sequences of rational numbers is Mike Shulman's "Brouwer's fixed-point theorem in real-cohesive homotopy type theory"
https://www.cambridge.org/core/journals/mathematical-structures-in-computer-science/article/abs/brouwers-fixedpoint-theorem-in-realcohesive-homotopy-type-theory/8270C2EAC4EE5D5CDBA17EEB3FF6B19E

**Comment by MadeleineBirchfield** [comment]
There is also Martin Escardó and Alex Simpson's paper "A Universal Characterisation of the Closed Euclidean Interval" published in 2001, where the authors explicitly state in section 8 that the Cauchy real numbers are not Cauchy complete. (they work internally in an elementary topos)
https://www.cs.bham.ac.uk/~mhe/papers/interval.pdf

**Comment by MadeleineBirchfield** [comment]
@mikeshulman Also, the Lubarsky paper was first published in 2007: 
https://www.sciencedirect.com/science/article/pii/S157106610700014X

**Comment by nicolaikraus** [comment]
A mathematical theorem lives in a precise setting that includes foundation and assumptions. It's not right to say that the Cauchy reals are not Cauchy complete in an absolute sense [1], and all the papers you cite work in a concrete setting. We're aware and used to the fact that different settings and assumptions change what theorems can be proved, so I don't really see a contradiction or problem.

When there's any risk of confusion, I usually talk about the "higher/quotient inductive-inductive Cauchy reals" or the "HoTT book Cauchy reals" in contrast to the "Cauchy reals via equivalence classes" or the "Cauchy reals that require choice". In principle, the book could give a precise name to the construction in Definition 11.3.2 and call it "higher inductive-inductive Cauchy reals". But one would then immediately want to drop the part "higher inductive-inductive" and only talk about the "Cauchy reals" anyway.

[1] Fwiw, this formulation sounds like an internal negative statement, which wouldn't be correct in any case; what is meant is that it's independent.

**Comment by awodey** [comment]
thanks for your comment @MadeleineBirchfield !
But may I suggest respectfully that saying that the HoTT book "attempts to appropriate" a well-defined concept in constructive math is asking for an argument.  Constructive math is old and wide, and I don't think there are any universally settled definitions, even of what counts as "constructive math".  Also, remember that the HoTT book is not intended as a foundation for constructive math, but just for math.

**Comment by MadeleineBirchfield** [comment]
@mikeshulman I've just had a long discussion with @andrejbauer and he stated in regards to the term "Cauchy real number"
>  completeness properties are the criterion by which we judge constructions. If some particular construction does not yield the desired completeness property, then it's unsuitable and does not warrant much attention (unless one revels in pathology), even though in some other setting it might be right.

The completeness property here is "Cauchy completeness" defined via Cauchy sequences, and Andrej writes
> There's no point in belaboring about the traditional definition of Cauchy reals in a setting where countable choice and LEM aren't available. That's the wrong construction because it doesn't give the desired competeness property.

Meanwhile I dug into the historical record and discovered that Cauchy real numbers were actually first defined by Georg Cantor in 1871, 14 years after the death of Augustin-Louis Cauchy, and so one could argue that the Cauchy real numbers as defined or constructed above should really be called "Cantor real numbers" and "modulated Cantor real numbers" respectively, since it is clear that the definition doesn't really have anything to do with either Cauchy completeness or Augustin-Louis Cauchy himself, unlike the case with Dedekind real numbers.
