### ISSUE TITLE
Use parentheses in the proof of Lemma 2.1.4(iii)

### ISSUE THREAD

**Issue by Bolpat** [HoTT/book#1135]
In the statement of Lemma 2.1.4(iii), you use (p⁻¹)⁻¹, but in the proof of Lemma 2.1.4(iii), you write p⁻¹ ⁻¹, while it probably should be (p⁻¹)⁻¹ as well. Of course, anyone can readily guess what is meant, but it still looks wrong.

**Comment by prime235711** [comment]
Agree. I think it's bad when they're incoherent.

**Comment by mikeshulman** [comment]
Yes, a pull request would be great if anyone wants to submit one.

**Comment by Bolpat** [comment]
PR is #1137
