### ISSUE TITLE
Provided Hashes in errata.pdf Not Found

### ISSUE THREAD

**Issue by jonaprieto** [HoTT/book#1142]
While I was trying to verify the amendments listed in some entries in the errata.pdf file, I ran into a problem with the provided Git hashes. I was expecting to use some of these hashes with the git checkout command, but I keep receiving an error stating that the specified hash was not found.

Here is an example using just the first hash from the pdf found at https://hott.github.io/book/errata-1357-gbe0b8e2.pdf:

```
$ git checkout gb29ea2f
error: pathspec 'gb29ea2f' did not match any file(s) known to git
```

How am I supposed to use these hashes? what if I want to check the exact commit that introduced the change described by the entry in the errata?

**Comment by mikeshulman** [comment]
You have to omit the "g"; the commit hash is just `b29ea2f`.

**Comment by jonaprieto** [comment]
True, it got a bit late here, didn't see that.
