### ISSUE TITLE
lemma 2.3.1 uses id whereas most other equality proofs use refl

### ISSUE THREAD

**Issue by bblfish** [HoTT/book#756]
lemma 2.3.1 uses the id function for defining d, whereas all the other use refl. Why this change?

**Comment by mikeshulman** [comment]
refl is the identity path; id is the identity function.

**Comment by bblfish** [comment]
yes, the question that is not clear for someone new to this field, is why here the identity function us used and not the refl identity path like in all the proofs on the previous pages.

**Comment by bblfish** [comment]
i suppose that in the case of 2.3.1 id is more handy because it is defined per type id(A), and that this proof requires just knowledge of the type, whereas in the proof of say 2.1.1 the conclusion D uses the refl  function, so that it is obvious how the two relate there....

I suppose you can close this, unless someone thinks that this could do with a footnote in the book.
Happy New Year.

**Comment by mikeshulman** [comment]
refl and id have different types.  One is a path, the other is a function.  The output of `transport` is not a path-type, so refl would be ill-typed here.  Instead we can use id as a function from P(x) to P(x).
