### ISSUE TITLE
`idtoeqv` is not equal to `transport id`

### ISSUE THREAD

**Issue by pcapriotti** [HoTT/book#765]
On page 89, it says that `idtoeqv` is (judgementally) equal to transport along the identity. That should probably be changed to refer to the *first component* of `idtoeqv` only (sometimes called `coerce`, although I'm not sure if the book names it explicitly). The type signature is also wrong, when interpreted as the type of the term containing `transport`.

**Comment by andrejbauer** [comment]
If you make a pull request, I'll buy you a beer when we meet.

**Comment by mikeshulman** [comment]
Is this resolved by #834?

**Comment by andrejbauer** [comment]
I think so.
