### ISSUE TITLE
In chapter 2, the notation ∏ (p : x = y) U is used instead of x = y -> U

### ISSUE THREAD

**Issue by 11Kilobytes** [HoTT/book#766]
In chapter 2 of the hott book, specifically on page 61, when speaking about the induction principle, the book says:
D: ∏ (x,y : A) ∏ (p : x = y) U

Whereas, for consistency with chapter 1, it should say:
D: ∏ (x,y : A) x = y -> U

I'm pretty sure that the path p doesn't need to be pi-bound because (currently) the path used doesn't affect what universe D(x, y, p) is in.

**Comment by andrejbauer** [comment]
Uhm, page numbers are unreliable What section is this precisely?

**Comment by 11Kilobytes** [comment]
It's before section 2.1, After the sentence, "Moreover, one of the amazing things about homotopy type theory is ..."

**Comment by 11Kilobytes** [comment]
Never mind, I have an old version of the HoTT book
