### ISSUE TITLE
Confusion about “Vble” structural rule in A.2.2 

### ISSUE THREAD

**Issue by veryfoolish** [HoTT/book#771]
In A.2.2 we have 

(x_1:A_1,...,x_n:A_n) ctx
---------------------------------- Vble
x_1:A_1,...,x_n:A_n  ⊢ x_i : A_i

Is 'Vble' supposed to mean we can 'pick out' a judgement in the context? 
i.e., does 'i' satisfy '1 <= i <= n'?

Or does it mean we can generate names 'free relative to a context'?
i.e., does 'i' satisfy 'n < i'?

More on this would be useful.

Ryan

**Comment by mikeshulman** [comment]
The former.

**Comment by veryfoolish** [comment]
It's actually pretty clear from the preceding paragraph; I was scanning and the 'i' made it difficult to parse. Unless you think this is particularly garrulous you can close the issue.
