### ISSUE TITLE
A correction to the "constructivity" section.

### ISSUE THREAD

**Issue by vladimirias** [HoTT/book#772]
In the paragraph:

"Using all types as propositions yields a “constructive” conception of logic (for more on which, see [Kol32, TvD88a, TvD88b]), which gives type theory its good computational character. For instance, every proof that something exists carries with it enough information to actually find such an object; and from a proof that “A or B” holds, one can extract either a proof that A holds or one that B holds. "

I propose to remove the phrase ", which gives type theory its good computational character".

**Comment by mikeshulman** [comment]
I agree; I also think we may be able to improve the rest of the paragraph with some rewording.  But can we discuss this at the already-open issue #764?
