### ISSUE TITLE
Is thm:transport-path really about "transportation in path spaces and pulled back fibrations?"

### ISSUE THREAD

**Issue by 11Kilobytes** [HoTT/book#778]
See this math overflow question: http://mathoverflow.net/questions/199242/can-someone-elaborate-on-a-categorical-homotopical-point-made-in-the-proof-that 

To put it briefly, I think that it is highly probable that the HoTT Book's phrasing of the proof that ∑2 = S^1 needs to be rephrased. The reason is that the type family `fun (x) f(x) = g(x)` isn't a pullback, since pullbacks don't enforce the restriction that the values of x that are plugged in to both sides of the equation have to be the same.

**Comment by mikeshulman** [comment]
I answered you on MSE.
