### ISSUE TITLE
Coercion from equivalences to functions

### ISSUE THREAD

**Issue by mikeshulman** [HoTT/book#784]
In some places we treat equivalences as functions, implicitly coercing away the witness of isequiv.  One such place is in the second and third sentences of the proof of Lemma 4.1.1:

"... we may assume that (f,e) is of the form idtoeqv(p) for some p:A=B. Then ... we may assume p is refl_A, in which case idtoeqv(p) is id_A".

Should we allow ourselves to do this?  (I think so.)  If so, ought we to be more explicit about it somewhere?  Where and how?

**Comment by mikeshulman** [comment]
(Issue raised by @Pierre-Yves-Gaillard at #782)

**Comment by Pierre-Yves-Gaillard** [comment]
What about changing "in which case idtoeqv(p) is id_A" to "in which case f is id_A"?

**Comment by mikeshulman** [comment]
Yes, I would like that better than the other change you suggested.  But I wonder whether there are other places that we do something like this.
