### ISSUE TITLE
Lack of examples of higher level relations in Section 2.6

### ISSUE THREAD

**Issue by nyraghu** [HoTT/book#785]
In the first para of Section 2.5 the book says, "Our goal in the rest of the chapter is to make explicit how this higher structure behaves in the case of the particular types defined in Chapter 1."  However, all the equations in Section 2.6 on Cartesian products are of level 1, that is, dealing with paths between points.  I don't know if this is the case with the remaining sections of Chapter 2 also.

It'd be good if the book can give at least one example of a higher level relation in Section 2.6, and similarly for the other sections of Chapter 2.  For instance, what is the relation between the homotopies of Lemma 2.1.4 for AxB, and the same homotopies for A and for B?  I think it's a misnomer to call Section 2.5 "The higher groupoid structure of type formers", and then give examples of only the the lowest level of relations in the following sections.

@pthariensflame Thanks for the pointer about editing.  I've corrected the typos here, and removed the two comments I'd used earlier to correct them.

**Comment by nyraghu** [comment]
I wrote, "It'd be good if the book can give at least one example of a higher level relation in Section 2.5, and similarly for the other sections of Chapter 2."  I meant Section 2.6, not 2.5.

**Comment by nyraghu** [comment]
I wrote, "I think it's a misnomer to call Section 1.5 "The higher groupoid structure of type formers", and then give examples of only the the lowest level of relations in the following section."  I meant Section 2.5, not 1.5.  Wondering if there's a way to correct typos in this issue/comment system.

**Comment by pthariensflame** [comment]
@nyraghu You should just be able to click the "edit" button (which look like a stylized pencil), and alter your comment arbitrarily.

**Comment by mikeshulman** [comment]
Well, even 1-groupoids are "higher" than sets, so I don't think the phrase "higher structure" is inappropriate even if we don't go beyond level 1.  And the higher-dimensional structure _is_ mentioned briefly to in section 2.6, by the sentence "The same is true for the rest of the higher groupoid structure considered in section 2.1".  But I suppose we could state one or two of the resulting equations explicitly.

**Comment by andrejbauer** [comment]
We could make forward references to the Eckmann-Hilton argument, and surely the associativity pentagon appears somwhere in the book as well. Or we can pull those two into Chapter 2.

**Comment by mikeshulman** [comment]
Eckmann-Hilton is already in section 2.1.  I think @nyraghu wants us to mention how this higher structure interacts with the type formers that are studied one by one in the second half of chapter 2.

**Comment by andrejbauer** [comment]
Sorry, I was speaking off the top of my head. Maybe we can kindly ask @nyraghu to find some desired examples in the book, and then we either move them or reference them.

**Comment by nyraghu** [comment]
I've already given one example which I would've found useful were it included.  Namely, in Lemma 2.1, item (i), let F(A,p) be the homotopy from p to p.refl_y.  Then, what is the equation which relates F(AxB,p) with F(A,ap(pr_1,p)) and F(A,ap(pr_2,p)), where p is a path in AxB?  (I think of this as a level 2 relation because it is about homotopies, i.e., paths between paths.)  Other examples I'd like to see are all the homotopies in Lemma 2.1.4.  Also, the equation relating the Eckmann-Hilton homotopy between alpha.beta and beta.alpha for AxB, and the Eckmann-Hilton homotopies for the factors A and B.

All these could be stated without proof as Theorems, and the reader could be asked to verify them himself.  I feel that even if one knows standard graduate level algebraic topology, deriving these relations is going to take time, and the temptation is to skip ahead without seeing even one example of a relation at a level greater than 1 for the Cartesian product type, and the other types discussed in the second half of Chapter 2.  Of course that may be harmless, but then it can be mentioned that these unstated equations won't be used in the rest of the book.
