### ISSUE TITLE
Induction principle remark

### ISSUE THREAD

**Issue by mobileink** [HoTT/book#788]
Page 50:  "Intuitively, the induction principle for the natural numbers expresses the fact that the only natural numbers are 0 and succ(n), so if we prove a property for these cases, then we have proved it for all natural numbers."

That seems plainly wrong to me. It's a non sequitur: the first part is ok, but the second part does not follow (and is also false).  A possible correction:  "... so if we prove a property P for 0, and we also prove the conditional 'if P is true for n, then P is true for succ(n)' then we have proved it for all natural numbers."

Unfortunately this would blow the following sentence out of the water:  "Applying this same reading to path induction...".  But path induction does not have an inductive step ("if P(n) the P(n+1)"), so you can't "apply this same reading to path induction".

**Comment by andrejbauer** [comment]
It may be a non sequitur, but is not plainly false. If you prove a property P holds for 0 and for every successor, then it holds. I agree that the text, as formulated now, is misrepresenting induction on natural numbers.

**Comment by mikeshulman** [comment]
Given the point that we're trying to make here (which is about path induction, not about natural numbers), it might be better to drop all mention of natural numbers and talk about, say, coproducts instead.

"Intuitively, the induction principle for A+B expresses the fact that the only elements of A+B are of the form inl(a) or inr(b), so if we prove a property for these cases, then we have proved it for all elements of A+B.  Applying this same reading to path induction...".

**Comment by mobileink** [comment]
Andrej: it depends on how you read it; you've inserted a universal quantifier, which is ok, but I think a more idiomatic and natural reading is " /of the form/ 0 and succ(n) /for some n/".  And proving P for 0 and succ(n) for some n plainly does not prove it for all n.

Mike: seems reasonable to me.  From my perspective the real problem is that "induction" is being used in two ways.  In my view if it does not involve a "next" clause in a conditional, it ain't induction.  That kind of induction is a proof device (or, a form of reasoning).  If you have finitely many forms, then you don't need induction, even if you have infinitely many values.  The "induction" principles for coproducts and paths look more like universal quantification to me. I suspect the use of "induction" in those cases derives from the idea that free generation "induces" structure or something like that.  That kind of induction (inducing) is a mathematical notion that happens only in the semantic domain.  In any case, perhaps you should include a passage somewhere explaining why it makes sense to use the term "induction" for path induction and similar (and how it relates to mathematical induction).

**Comment by awodey** [comment]
On May 26, 2015, at 2:01 AM, Gregg Reynolds <notifications@github.com> wrote:
> 
> Andrej: it depends on how you read it; you've inserted a universal quantifier, which is ok, but I think a more idiomatic and natural reading is " /of the form/ 0 and succ(n) /for some n/". And proving P for 0 and succ(n) for some n plainly does not prove it for all n.
> 
the convention that a free variable is implicitly universally quantified is very well-established — like for 100 years (cf. Russell, On Denoting).
> Mike: seems reasonable to me. From my perspective the real problem is that "induction" is being used in two ways. In my view if it does not involve a "next" clause in a conditional, it ain't induction.
> 
that's your view, but not the view being taken in the Book.  
A more general notion of induction is being invoked there, and it is already explained quite carefully.

**Comment by mikeshulman** [comment]
Probably the desire to emphasize the similarity to N-induction, hence justify the term "induction", was the reason we compared to N here rather than to a coproduct.
