### ISSUE TITLE
Theorem 10.2.10

### ISSUE THREAD

**Issue by jamescheney** [HoTT/book#793]
In the statement and proof of theorem 10.2.10, I think the formula A \cong B should be A \simeq B.  (The proof refers to an "isomorphism" but A and B are sets; when this theorem is used in cor. 10.2.11, the proof refers to an "isomorphism" A \simeq B obtained using the theorem.)

**Comment by jamescheney** [comment]
NB this is in first-edition-611-ga1a258c.

**Comment by mikeshulman** [comment]
Interesting point, there is a mismatch in notation.  However, I would be more inclined to change the \simeq in 10.2.11 to a \cong.  In general we do permit ourselves to use the word "isomorphism" for equivalences between sets (this is mentioned in the paragraph after Example 2.4.9) and I think this carries over to the notation \cong (although perhaps we should mention that explicitly somewhere).

**Comment by jamescheney** [comment]
OK as long as the meaning is clear here.  The index of symbols in my print copy (first-edition-3232-g28e4374) lists three senses of \cong: type of isomorphisms in a (pre)category, type of isomorphisms between precategories, and (with a dagger) the type of unitary isomorphisms.  None of these seems to apply if we are just talking about two sets (not objects of a category).

**Comment by mikeshulman** [comment]
Generally we wait to close the issue until the pull request has been merged (merging it actually automatically closes the issue).

**Comment by jamescheney** [comment]
Oops again - I didn't read carefully and thought you had made the change to the main repository.
