### ISSUE TITLE
Configure travis to automatically post nightly builds

### ISSUE THREAD

**Issue by mikeshulman** [HoTT/book#799]
See discussion at #794.

**Comment by JasonGross** [comment]
Do you want to post the builds to the [book wiki](https://github.com/HoTT/book/wiki) / to `gh-pages` (then available at `http://hott.github.io/book/$filename`), or do you want to post them to wordpress or something?  If the former, I can make you a pull request that does that, if you give me a command that generates the pdf name you want.  Otherwise, you'll have to write a script that uploads the book to wordpress, and I can go find the instructions for encrpyting whatever authentication key will need to be in the environment to do that.

**Comment by andrejbauer** [comment]
We can link to the `github.io` wiki from wordpress, no need to upload.

**Comment by mikeshulman** [comment]
Are we thinking of this as _replacing_ the PDFs currently hosted on wordpress?  I was originally thinking of it as _supplementing_ the "official releases" with "nightly builds".  Making these the official releases would of course have the advantage of keeping those very up to date, but it would have the disadvantage that the released PDFs would be out of sync with the paper versions available from lulu.  But maybe that's no big deal as long as we make it clear on the page and are better about updating lulu periodically?

Either way, it's fine to post these on github.  If they're replacing the official releases, then we'll want to `make` all the versions (online, ebook, letter, a4, and errata), and probably also tag the filenames with `git describe` output.

**Comment by andrejbauer** [comment]
We can have both on the wordpress site: the "official" release which is in sync with the printed book *and* nightly builds.

**Comment by mikeshulman** [comment]
I guess there's no reason not to have nightly builds of all versions.

```
make hott-online.pdf && mv hott-online.pdf hott-online-$(git describe | sed s/first-edition-//).pdf
make hott-ebook.pdf && mv hott-ebook.pdf hott-ebook-$(git describe | sed s/first-edition-//).pdf
make hott-letter.pdf && mv hott-letter.pdf hott-letter-$(git describe | sed s/first-edition-//).pdf
make hott-a4.pdf && mv hott-a4.pdf hott-a4-$(git describe | sed s/first-edition-//).pdf
make errata.pdf && mv errata.pdf errata-$(git describe | sed s/first-edition-//).pdf
```

**Comment by JasonGross** [comment]
Do you want previous nightly builds to be accessible, or only the latest ones?

**Comment by andrejbauer** [comment]
If the file name contains the git commit hash then it will be a bit more difficult to link to it from Wordpress. Does Github support symbolic links?

**Comment by mikeshulman** [comment]
@JasonGross I don't really see any reason for the previous ones to be accessible.

@andrejbauer hmm, good point.  I do like the idea of having filenames labeled with version number.

**Comment by JasonGross** [comment]
I would be surprised if symlinks accomplish what you want; I suspect either the pdf will be displayed under the symlink's filename, or they won't be supported, rather than actually redirecting the user to the underlying pdf, which I think is what you'd want.

**Comment by mikeshulman** [comment]
Yes, I think what he meant was redirects.

**Comment by mikeshulman** [comment]
One possibility would be to create a "nightly builds page" on the github wiki which links to all the pdfs rather than linking directly to them from wp.  That way travis can update the links on the wiki page too.

**Comment by JasonGross** [comment]
[GitHub seems to support redirects](https://help.github.com/articles/redirects-on-github-pages/).

**Comment by JasonGross** [comment]
But I don't think those redirects can be made to do what we want (they seem to work for blog posts, not pdfs?).  Does someone else want to look into it?

**Comment by mikeshulman** [comment]
Yeah, that doesn't seem like it would work for pdfs.  Let's just make a nightly builds wiki page; people who want the latest and greatest can stand to click on two links instead of just one.

**Comment by JasonGross** [comment]
@mikeshulman, do you want to edit the wiki and make a page with dummy placeholders, and then I can have the script base its page on that.  (Namely, I'm asking you to decide the ordering, and the text/style/formatting, etc.)

**Comment by mikeshulman** [comment]
https://github.com/HoTT/book/wiki/Nightly-Builds.  It would be great if the date and version marker on the page could also be updated: the version marker should be the literal output of `git describe`, while the date would ideally be the date of the most recent commit.

**Comment by mikeshulman** [comment]
Thanks for doing this!

**Comment by JasonGross** [comment]
What if we have travis generate a javascript/jsonp file that encodes the latest nughtly builds, something like
```javascript
setNightlyBuilds({
  "on-screen": "//hott.github.io/book/nightly/hott-online-928-g5d7cb3f.pdf"
  "e-book": "//hott.github.io/book/nightly/hott-ebook-928-g5d7cb3f.pdf"
  "letter": "//hott.github.io/book/nightly/hott-letter-928-g5d7cb3f.pdf"
  "A4": "//hott.github.io/book/nightly/hott-a4-928-g5d7cb3f.pdf"
  "errata": "//hott.github.io/book/nightly/errata-928-g5d7cb3f.pdf"
});
```
and then the wordpress site could include this javascript file in the template on the site, as well as a local javascript file that defined a `setNightlyBuilds` function to look for a div with a particular id on the site, and update the div with the appropriate content.

**Comment by JasonGross** [comment]
The `setNightlyBuilds` function would presumably be something like
```javascript
function setNightlyBuilds(urls) {
  var types = ["on-screen", "e-book", "letter", "A4", "errata"];
  for (var i = 0; i < types.length; i++) {
    var elem = document.getElementById("nightly-" + types[i]);
    if (elem !== null) {
      elem.href = urls[types[i]];
    }
  }
}
```
and then we'd put things like `<a href="#" title="Most recent build for on-screen viewing" id="nightly-on-screen">[nightly]</a>` on the book page.

**Comment by mikeshulman** [comment]
It's a nice idea, but I don't think we can put javascript on a wordpress.com site.

**Comment by JasonGross** [comment]
Oh, I was looking at wordpress.org.

**Comment by mikeshulman** [comment]
Yeah, I really wish they'd used a different name for the hosting site and for the software, it's so confusing.

**Comment by mikeshulman** [comment]
I have another idea, hang on a bit.

**Comment by andrejbauer** [comment]
But it should be simple. Whatever piece of code generates the filenames of the current PDFs can also produce symlinks to those files. Or we simply make an additional copy of each file, but with a fixed filename. Space is cheap.

**Comment by mikeshulman** [comment]
If we make another copy with a fixed filename (or symlink it at server level, rather than redirecting), then people who download the file through that link will get a file without the version marker in the name.  Which we might decide is fine, but if so, then there's no point to also having the files _with_ the version marker in the name.

**Comment by andrejbauer** [comment]
Then make it a [303](https://en.wikipedia.org/wiki/HTTP_303).

**Comment by JasonGross** [comment]
GitHub pages doesn't support server redirects.  I can have travis generate the relevant .htaccess file (or whatever other server configuration file is necessary), but it'd need to be hosted somewhere other than GitHub pages.

**Comment by andrejbauer** [comment]
I have a server with apache2 and ssh running, if that helps.

**Comment by awodey** [comment]
we can use Saunders for this.

**Comment by andrejbauer** [comment]
Yup, that would work too. Both seem to have ssh and http servers running, which is what's needed.

**Comment by JasonGross** [comment]
If you want to [encrypt a login token for travis to use](https://github.com/HoTT/book/commit/d55fff5874dff7bff967457e8cc97755d60db1a8) and tell me where to shove the .htaccess file, I can get travis to do this.  Alternatively, if you want to set up something fancier, where the server listens for commit notifications from github and then fetches the .htaccess from github pages, you can set that up, and I can have travis simply generate the file.

**Comment by mikeshulman** [comment]
I don't think the server needs to listen to commit notifications; it just has to fetch the .htaccess every night.

**Comment by mikeshulman** [comment]
Okay, I've figured out how to set up a redirect: http://saunders.phil.cmu.edu/book/hott-online.pdf should redirect you to the current nightly build (as of right now).  What remains is to configure it to automatically update the pointer when new builds are made.  We can't use .htaccess because saunders is running nginx rather than apache, and nginx appears to be kind of dogmatic in its dislike of htaccess files; so the redirect has to be done in a conf-file snippet inside /etc/nginx.  In theory we could have travis create that snippet and get it pushed or pulled to saunders daily or on builds, but for security I don't really like the idea of allowing Travis (even in principle a script that we wrote running on travis) to create arbitrary configuration for saunders' web server.  What I'd like is for a cron job on saunders to be able to hit some URL that will return nothing but the current version marker of the nightly builds, e.g. `928-g5d7cb3f`; then the script can check that it's the right length and purely alphanumeric before splicing it into the web server configuration.  Can you set Travis up to do that?

**Comment by mikeshulman** [comment]
(Reopening this issue since we are having active discussion here.)

**Comment by andrejbauer** [comment]
Yeah, Mike's plan sounds good.

**Comment by andrejbauer** [comment]
It still pains me that we need to involve *three* servers in what should be doable with just two.

**Comment by JasonGross** [comment]
I can set travis up to do that, but it might take a week; I'm at mathcamp at the moment.  It should be pretty simple if you want to do it, just pipe the output of the git describe command to a file in the build-nightlies script at top level, and, I think, have it echo the name of the file so that the etc/ci script picks it up.

**Comment by mikeshulman** [comment]
@JasonGross how about it now?  (Sorry, I just don't have time to learn to use Travis myself right now...)

**Comment by JasonGross** [comment]
@mikeshulman #845 should do it, if I set things up right.

**Comment by mikeshulman** [comment]
Looks good, thanks!  When I get a moment I'll configure saunders.

**Comment by mikeshulman** [comment]
Okay, I've written a script on saunders that hits your URL and updates the redirect.  For now I set it to run daily.  Unfortunately I guess that means that whenever a new change is committed, the links will break for the time in between when Travis runs and when the redirect script runs...

**Comment by JasonGross** [comment]
We could keep the old ones lying around.  Or we could timestamp them and only remove the ones that are older than a day.

**Comment by mikeshulman** [comment]
Keeping them around for a day sounds like a good idea to me.

**Comment by JasonGross** [comment]
Should we reopen this issue, then, or make a new one?

-Jason
