### ISSUE TITLE
The Second Presentation and induction from functions

### ISSUE THREAD

**Issue by heatherclarke** [HoTT/book#804]
In A.2.5 dependent Sigma-types are defined avoiding any use of function types, for example the input g in Sigma-ELIM and Sigma-COMP is just a term with free variables x, y which I like.

But how do you use this when you want to induct using as input g an actual function (i.e. g: A -> B -> C) , for example as is done in the paragraph below Theorem 1.8.1 to make binary coproducts, where P is not made using lambda-abstraction?

**Comment by mikeshulman** [comment]
If `g` is a function of two variables, then `g(x,y)` is a term with free variables `x` and `y`.
