### ISSUE TITLE
Why brackets in $\Prod_{(x:A)} ...$?

### ISSUE THREAD

**Issue by danielgerigk** [HoTT/book#805]
I would like to know why in the notation for dependent function types sometimes there are (round) brackets around the thing that is being quantified over ( - like this: "$\Prod_{(x:A)} ...$" - ) and sometimes there are no brackets ( - "$\Prod_{x:A} ...$"). Both notations can already be found in the very beginning of chapter 1.4, but also later.  The same applies to dependent pair types.
Did that occur just by accident, or does it have a meaning?

**Comment by mikeshulman** [comment]
There are parentheses whenever there is more than one Pi or Sigma in sequence, to help visually separate the variables being quantified over.  When there is only one Pi or Sigma, the parentheses are omitted as unnecessary.

**Comment by danielgerigk** [comment]
Ah ok, that sounds reasonable... thanks for your answer.
