### ISSUE TITLE
abuse of language: "f : A \equiv B" vs "f: A -> B"

### ISSUE THREAD

**Issue by danielgerigk** [HoTT/book#819]
In the text directly following Axiom 2.10.3 (Univalence), up to (and including) Lemma 2.10.5, terms $f: A \equiv B$ are freely identified with terms $f: A -> B$ that have the (mere) property of being equivalences. Should this "abuse of language" be mentioned in the text, or would that be too pedantic? I'm not sure.

**Comment by mikeshulman** [comment]
It is mentioned in the paragraph right after (2.4.11).
