### ISSUE TITLE
ZFC with urelements

### ISSUE THREAD

**Issue by bblfish** [HoTT/book#836]
Perhaps it would be worth mentioning that HoTT encompasses ZFC with urelements.

Here is my proof:

take the Set Human of all human beings such that `isSet(Human)`
Given that

```HoTT
socrates: Human
```
yet 

```HoTT
socrates =!= 0
```

Also `socrates` is not itself a set.

In ZFC all sets are constructions from the empty set.

**Comment by andrejbauer** [comment]
I wouldn't say that HoTT "encompasses" ZFC with urelements. Rather it *models* ZFC with urelements, just like it models ZFC. While your proof is not really suitable for the book, we could add an exercise in which we ask for an adaptation of the ZFC construction in which the type V of sets contains a prescribed type Ur of urelements.

**Comment by bblfish** [comment]
Great. I'll defer to what you think is the better name of course, being just a beginner. ( for others coming across this thread, we had a [discussion of this on the HoTT mailing list](https://groups.google.com/d/msg/hott-cafe/m8Mk0HfrEtc/3_MJJAoBt-oJ) last week on this. So I am happy that my intuitions are about right. :-)

**Comment by bblfish** [comment]
I am studying chapter 10 now, which is very helpful, so I'll get back to this when done.
