### ISSUE TITLE
missing definition of named equivalence

### ISSUE THREAD

**Issue by bblfish** [HoTT/book#841]
On p78 of the July 12 2015 version of this github book, in section 2.4, the following symbolism is introduced, with a greek letter on top of the equivalence symbol:

![named-equivalence](https://cloud.githubusercontent.com/assets/124506/8888157/c3e731c6-32a2-11e5-81d6-1af6f70ffc92.png)

I could not find a definition of it ( though I can guess that it is just naming the relation ). I could not find a pointer in the _Index of Symbols_ either.

I find that passage very hard to read.

**Comment by andrejbauer** [comment]
"July 12" version of the book is meaningless. Please tell us instead the commit hash found on the page after the torus picture (where the copyright is stated). It looks something like

     Book version: first-edition-820-g5c551bc

**Comment by mikeshulman** [comment]
Also, "p78" is ambiguous unless referring to a particular size: hott-online, hott-ebook, etc. have different paginations.  But "section 2.4" and your description are enough to find the place.

I agree that that passage is perhaps a little too brief.

**Comment by bblfish** [comment]
sorry for the lack of precision.  The version I was dealing with is

```
Book version: first-edition-924-ge09515e
```

**Comment by mikeshulman** [comment]
Does #843 look better to you?

**Comment by bblfish** [comment]
( ah sorry, travelling and having difficulty getting to my computer. I'll verify when I get back to it )
