### ISSUE TITLE
Adjunctions question

### ISSUE THREAD

**Issue by bblfish** [HoTT/book#847]
I am having trouble getting the second adjunctions formula in 9.3 to work on a simple example. So I am wondering if it is correct ( though I guess it is and I am making a mistake ).
 1. (εF)(Fη) = 1F
 2. (Gε)(ηG) = 1G.

I have no trouble with drawing out the first one as seen in the top diagram of the attached image,
after the following transformation which I get from lemma 9.2.8 

 ((εF)(Fη))a = (1F)a 
=>
   εFa ◦ F(ηa) = 1Fa

![hott-adjuntions 9 3](https://cloud.githubusercontent.com/assets/124506/9137861/d9468eb2-3d20-11e5-9211-730bbb829381.jpg)

But when I try to draw out the diagram for the second formula in a similar way I find I cannot get all the edges to touch. ( see the lower diagram I drew out as it is clearer than the top one )

 ((Gε)(ηG))b = (1G)b
=>
G(εb)◦ηGb = 1Gb

Starting from Gb on the A side I can follow my green arrow for ηGb to GFGb. But then εb is a blue arrow on the other side ( In the B category ) and there is no arrow to there. It would perhaps work if the formula were instead.

 ((ηG)(Gε))b = (1G)b
=>
 ηGb ◦ G(εb)= 1Gb

I am probably making a mistake somewhere, but as I have been going over this for quite a few hours I thought I'd check....

**Comment by mikeshulman** [comment]
I don't understand what your pictures are supposed to mean, but you just need to apply the functor G to εb, as the equation says, to get a morphism from GFGb to Gb.

**Comment by bblfish** [comment]
Ah I see G(εb) is applying a functor to an arrow...
It was very hot here in Austria (37C), and somehow I completely forgot that possibility.

**Comment by bblfish** [comment]
Ok that makes a lot more sense then. This is the diagram I now have:

![hott-adjuntions 9 3-v2](https://cloud.githubusercontent.com/assets/124506/9149388/b14fa038-3da7-11e5-9a11-216966c71006.jpg)

( it was very hot here yesterday 37C and up ). Thanks for helping me get unstuck. :-)

**Comment by andrejbauer** [comment]
Here are the [triangle identities](http://ncatlab.org/nlab/show/triangle+identities) in nLab, does that help?

**Comment by andrejbauer** [comment]
By the way, in your pictures you have arrows between objects labeled G and F. This is strange and also a bit dangerous because it induces faulty intuitions. A functor F takes an object a in one category to an object b = Fa in another, but there is no arrow "F" from a to Fa because they do not even live in the same category. (The unit η gives you such an arrow η_a: a → Fa.)

**Comment by bblfish** [comment]
@andrejbauer I try to refer often to ncatlab, though I find it difficult to read often as I get lost in the hyperlinks which I need to understand most definitions there.
Currently I am reading the HoTT book and Awodey's "Category Theory" 2nd edition by OUP.

Still I redid the diagrams to correspond closer to the triangle identities of ncatlab. It seems to fit there. 
I also tried to refer closer to the definitions of the HoTT book, which led me to this: 

![hott nlab-zigzag](https://cloud.githubusercontent.com/assets/124506/9150564/f2ea61da-3ddf-11e5-9368-ff449ec7d43d.jpg)

I feel quite confident here with the b = Fa is correct. I am not quite sure how I am being misled...

**Comment by bblfish** [comment]
At least I am able to continue reading the book... And since there was ( as expected ) no problem in the book, I'd better close this issue.

PS @andrejbauer it is difficult to read some of the diagrams on ncatlab for triangle identities.
