### ISSUE TITLE
Equivalence between retractions and split surjections

### ISSUE THREAD

**Issue by Pierre-Yves-Gaillard** [HoTT/book#849]
We could mention the fact that the notion of split surjection, defined in Section 4.6, is equivalent to the notion of retraction, previously defined in Section 3.11.

For more details, see https://groups.google.com/forum/#!topic/hott-cafe/XlHtBteQdv4

**Comment by andrejbauer** [comment]
By the way, a working mathematician even has [a hard time seeing](http://mathoverflow.net/questions/189180/topological-retraction-vs-categorical-retraction) that a retraction in category theory is the same thing as a topological retraction (an idempotent continuous endomap).
