### ISSUE TITLE
Unclear abuse of notation in the definition of the free group as a set-quotient.

### ISSUE THREAD

**Issue by 11Kilobytes** [HoTT/book#850]
The relevant paragraph occurs near line 1657 of hits.tex, at the time of posting this issue. We first say that i : F'(A) -> F'(A), and then we use the same symbol i to refer to a map between List(A + A) and itself. This isn't really wrong of course, since the endomap on List(A + A) descends to the quotient, and we use this to define an endomap on F'(A). This may confuse the reader.

**Comment by andrejbauer** [comment]
Please give subsection number instead, the way you referenced the text is annoying as most of us just fire up the PDF and look at what you're saying.

**Comment by mikeshulman** [comment]
It's theorem 6.11.7.  I think the intent is that `i` doesn't actually ever refer to a map on List(A+A), rather in the second display in that proof we have just neglected to notate the quotient map from List(A+A) to F'(A).  I guess we ought to notate it.
