### ISSUE TITLE
Proof of Lemma 6.12.4

### ISSUE THREAD

**Issue by Pierre-Yves-Gaillard** [HoTT/book#854]
It seems to me there are a couple of typos in the proof of Lemma
6.12.4, some of which can be fixed in more that one way. (There are
six displays in the proof; I'll call them Display 1,..., Display 6.)

(In the tex file the proof starts at Line 1874:

https://github.com/HoTT/book/blob/master/hits.tex#L1874 .)

Observation 1. I think all expressions of the form u▪v (in the proof
of Lemma 6.12.4) should be changed to v▪u. (Here ▪ denotes the
concatenation of paths --- command \ct in the tex file. There are three
expressions of the form u▪v in the proof, one in Display 4, two in
Display 5.)

To state the other observations, I'll denote the slanted c's occurring
in math mode by c, and the straight c's occurring in math mode by cc
(\cc in the tex file).

Observation 2. I think the three occurrences of ap_{x ↦ c(g(b),x)} 
should be changed to ap_{x ↦ cc^~'(g(b),x)}. (As we have 
cc^~'(a,x) :≡ (cc(a),x) by the beginning of the proof of Lemma 6.12.3, 
we could also use ap_{x ↦ (cc(g(b)),x)}, but I have a slight preference 
for ap_{x ↦ cc^~'(g(b),x)}. The expression ap_{x ↦ c(g(b),x)} occurs in 
Displays 3, 4 and 5.)

Observation 3. I think refl_{g(b)} in Display 5 should be changed to
refl_{cc(g(b))}.

***

Here are the other potential typos I found in the same chapter:

(1) Proof of Lemma 6.10.3, second paragraph, first sentence: 
g(x) = \overline{g\circ q} should be changed to 
g(x) = \overline{g\circ q}(x).

https://github.com/HoTT/book/blob/master/hits.tex#L1227

(2) The % at the end of Lines 1789 and 2104 should be removed.

https://github.com/HoTT/book/blob/master/hits.tex#L1789

https://github.com/HoTT/book/blob/master/hits.tex#L2104

(3) Proof of Lemma 6.12.3, after the display: pp(b) : f(b) = g(b) should
be changed to pp(b) : cc(f(b)) = cc(g(b)), where pp and cc mean
"straight p" and "straight c".

https://github.com/HoTT/book/blob/master/hits.tex#L1859

(4) In the second sentence after the proof of Lemma 6.12.4, apd_f should
be changed to apd_k.

https://github.com/HoTT/book/blob/master/hits.tex#L1918

**Comment by mikeshulman** [comment]
Observation 2 is fixed by #855; the others by #856.  Thanks!
