### ISSUE TITLE
Proposal for an alternative description of the cumulative hierarchy of sets V

### ISSUE THREAD

**Issue by danielgerigk** [HoTT/book#861]
Is the following an accurate description of the cumulative hierarchy of sets V (as found in Definition 10.5.1)?

**Definition.** Define V to be the inductively generated *set* generated by $set : (\sum_{A:U} A \hookrightarrow V) \to V$, where $A \hookrightarrow V$ stands for $\sum_{f:A \to V} \prod_{x,y:A} f(x)=f(y) \to x=y$.

*UPDATE: I gave the constructor a name ("set"), and specified "Set" to "Set_U". Furthermore, I later changed "$set : (\sum_{A:Set_U} ...$" to "$set : (\sum_{A:U} ...$", following the suggestion by Steve Awodey below.*

*UPDATE: I'm sorry, but I had to make another adjustment: I changed the definition of $A \hookrightarrow V$ from $\sum_{f:A \to V} \prod_{x,y:A} f(x)=f(y) \to x=y$ to $\sum_{f:A \to V} \prod_{a:A} isProp(fib_f(f(a)))$. This is necessary to ensure that for every $(A,f) : \sum_{A:U} A \hookrightarrow V$ it follows that $A$ is a set.*

*UPDATE: I just found out that the previous update was unnecessary: if a map $f : A \to V$, where A is any type and V is a set, is injective in the sense that (there is a term of type) $\prod_{x,y:A} f(x)=f(y) \to x=y$, then it follows that for every $a:A$ the fibre $fib_f(f(a))$ is a mere proposition, and that $A$ is a set.*

**Comment by andrejbauer** [comment]
What is $Set$? Do you mean the 0-types?

**Comment by danielgerigk** [comment]
Yes.

**Comment by danielgerigk** [comment]
The 0-types in $U$, to be precise. And I assume $U,V:U'$, as in Chapter 10.5 ("The cumulative hierarchy").

**Comment by mikeshulman** [comment]
I would say it's intuitively correct, but it's much more fishy as the type of a constructor than the one used in the book, because it contains path-types of V (the type being defined) in negative position.

**Comment by danielgerigk** [comment]
Sorry, I can't comprehend your comment... from my understanding, this inductive definition is strictly positive. (Note that $A \hookrightarrow V$ is defined as $\sum_{f:A \to V} ...$, not as $\prod{f:A \to V} ...$.)
The *induction principle for V* would say that to define/prove $\prod_{x:V} P(x)$ (for a "predicate" $P:V \to U$), it suffices to define/prove $P(set(A,f))$ for every $(A,f) : \sum_{A:Set_U} A \hookrightarrow V$ having the property $\prod_{a:A} P(f(a))$.

**Comment by andrejbauer** [comment]
If we unfold your definition we get something like

    Inductive V := 
      | set : ∑ (A : U) (f : A → V) . ∏ (x y : A) . f x = f y ➝ x = y

This does not have the correct shape for an inductive definition. The `set` constructor must be a map into `V` but it is not.

**Comment by danielgerigk** [comment]
The set constructor *is* a map into V.
Btw: how did you include the latex in your comment? Is it a picture?

**Comment by mikeshulman** [comment]
Andrej used unicode, not latex; they're just utf8 characters.  Andrej, I think what he's proposing is (if we unwind a map out of a Sigma into a Pi)

```coq
Inductive V :=
  | set : forall (A : U) (f : A -> V), (forall (x y : A), f x = f y -> x = y) -> V.
```

This is not strictly positive in `V` and its identity types, because `f x = f y` is an identity type of `V`, but it occurs in the domain of a function that is in the domain of the constructor.

**Comment by danielgerigk** [comment]
Ah, okay; but I don't consider that to be a problem. Technically you're most probably right - "probably" because I don't know the exact definition of strict positivity, only what I've read about it in the book. But according to my intuition, this inductive definition should still be considered admissible to define a valid inductive type. After all, the induction principle looks quite pleasant, too.
I'm probably going to write more on this in a few days (or weeks).

**Comment by danielgerigk** [comment]
Sorry Mike, I misunderstood you: you never said that the definition is not strictly positive *in V*, but only claimed that it's not strictly positive *"in V and its identity types"*. But as I said, I'm fine with that. :)

**Comment by awodey** [comment]
this version restores the condition A : U, rather than the proposed A : Set, which we have considered before.
requiring f : A —> V to be monic is essentially building in Lemma 10.5.6.  
It’s similar to replacing U with Set, in that it builds a factorization of arbitrary f : A —> V into the specification of V.

**Comment by danielgerigk** [comment]
Yes, you're right, Steve!

**Comment by mikeshulman** [comment]
You're free to "be fine with" anything you like, but semantically, it's hard to justify non-strictly-positive inductive definitions, and some of them are even inconsistent, as explained in section 5.6.  The fact that it's the identity types of V rather than V itself that appear negatively here doesn't make things any better; in fact I would say it probably makes them even worse, since even positive occurences of the identity type of the type under definition are more difficult (though not, perhaps, impossible) to make sense of semantically.

**Comment by danielgerigk** [comment]
I have thought about what you (Mike) said, and now accept the need to have strict positivity (which shall *include* conditions on the identity types of the type in definition). In order to be justified to claim that *there is* a universal (initial) type realizing the constructors of an inductive definition, you *better have* strict positivity.

So I guess my "definition" above is not really a definition, properly speaking, but more of a description of a universal property which shall characterize the inductive type to be generated. And what remains to be done after that is an *existence problem*: to prove that for every set W which satisfies that same universal property, there is an (essentially) unique *injection* $V \subseteq W$ which is compatible with the universal property. In the case at hand, this should be possible to be done using the definition of V which is given in the book.

**Comment by danielgerigk** [comment]
In other words, the function $set : T(V) \to V$ is a homotopy-initial T-algebra, where the functor $T : (Set_{U'})_{\righthookarrow} \ (Set_{U'})_{\righthookarrow}$ is defined by $T(X) := \sum_{A:U} A \hookrightarrow X$, and where $(Set_{U'})_{\righthookarrow}$ shall denote the category with $Set_{U'}$ as objects and only inclusions (between sets in $Set_{U'}$) as morphisms.

**Comment by mikeshulman** [comment]
The discussion here seems over, and it doesn't seem to have concluded that anything should be added to or fixed in the book, so I'm closing the issue.
