### ISSUE TITLE
yoneda lemma inverse proof functor misalignment?

### ISSUE THREAD

**Issue by bblfish** [HoTT/book#862]
In Theorem 9.5.4 the last part of the proof shows that the two natural transformation are inverses.
I am studying the first part of the proof and god stuck
```
αa′(f) = αa′(ya(a′,a)(f))
```
`f` is defined as of type `homA(a′, a)`.
The yoneda embedding is defined as `y: A → SetAop`
from this and `a: A` we deduce that `ya: SetAop` ie `ya` is a functor `Aop → Set`

From definition 9.2.1(ii) `F(a,b): homA(a,b) → homB(Fa, Fb)`
so in this context

`ya(a',a): homAop(a',a) → homSet(ya(a'),ya(a))` given that `ya` is a functor `Aop → Set`

but we have defined `f: homA(a',a)` and not `f: homAop(a',a)` which is what would be needed, so we can't apply f as it is done in the book with `ya(a',a)(f)`

**Comment by mikeshulman** [comment]
I guess it should be `$\alpha_{a'}(f) = \alpha_{a'}(\mathbf{y}a_{a,a'}(f)(1_a))$`?

**Comment by bblfish** [comment]
As far as I understand it seems like the `f` would then fit. But then one has to explain the switching of `a,a'` to `a',a`  below.

**Comment by mikeshulman** [comment]
It would also be `a,a'` on the next line.  Is there somewhere else too?

**Comment by bblfish** [comment]
Well it would go all the way to the end, since the conclusion is that `F(a',a)( f )(x)` which I think is what is trying to be proven. So at some point `a,a'` has to switch to `a',a` . I am not sure where the swich needs to happen.

**Comment by bblfish** [comment]
I tried following the argument from the end to the beginning. Here's what I wrote down in my notes a couple of days ago:

```
F(a',a)(f)(x) // so here we must assume that `f: homAop(a',a)` ie `f: homA(a,a')`
```

So it seems that this direction of f problem has worked its way all the way to the conclusion.

What if we do assume that `f:homAop(a',a)`

Then the argument continues from bottom to top like this:

```
F(a',a)(f)(x)
       = F(a',a)(f)(𝛂a(1a)) // by substitution on x
       = (F(a',a)(f) ◦ 𝛂a)(1a) // seems reasonable but I have not found the exact theorem this stems from
```       

The next step involves the naturality axiom which adopted to the symbols used here is

> For functors `ya, F: Aop → Set`, natural transformation `𝛂: ya → F`, for each `a,a': A` then for any `f: homAop(a',a) ≡ homA(a,a')`  we have `F(a',a)f ◦ 𝛂a' = 𝛂a ◦ ya(a',a)(f)`

but then the substitution won't work. We need instead `F(a,a')f ◦ 𝛂a = 𝛂a' ◦ ya(a,a')(f)`
ie we need `f: homAop(a,a') ≡ homA(a',a)`

But then it looks like we need to move the changes all the way to the conclusion, which should be `F(a,a')(f)(x)`. Would that work?

```
F(a,a')(f)(x) // conclusion
       = F(a,a')(f)(𝛂a(1a)) // by substitution on x
       = (F(a,a')(f) ◦ 𝛂a)(1a) // seems reasonable but I have not found the exact theorem this stems from
       = (𝛂a' ◦ ya(a,a')(f))(1a)
```

which is what you are proposing. 

Now we just need to check that the new conclusion is indeed the thing we want to proove.

**Comment by mikeshulman** [comment]
> Now we just need to check that the new conclusion is indeed the thing we want to prove.

It is.

I expect that this happened because whoever wrote that (perhaps me) was thinking of a contravariant functor as "a functor on A that reverses arrows" rather than "a functor on A^op", which is often convenient; but of course the latter is (nowadays) its formal definition.

**Comment by mikeshulman** [comment]
By the way, your "seems reasonable" line is just the definition of function composition.
