### ISSUE TITLE
A remark by Thomas Streicher

### ISSUE THREAD

**Issue by andrejbauer** [HoTT/book#866]
Thomas Streicher says that we misinterpreted one of his theorems:

> Triggered by our dicussion I looked up the little remark on p.395 of
the HoTT book where it is said in the 3rd paragraph of "Notes" that in
Th.4.13 of my old book I would have shown how to interpret normal forms
in a contextual category. I was quite puzzled when I saw this the
first time. And actually, it's a misunderstanding. What I write \equiv
is not convertibility but \alpha-convertibility. The intention of
Th.4.13 rather was that \alpha-convertible terms can't have different
\Pi-types. I needed this for eliminating type application.

He's talking about Appendix A notes, 3rd paragraph. We should fix this.

**Comment by mikeshulman** [comment]
The simplest fix would be to just remove the offending sentence.  Do we need to replace it with anything, and if so, what can we replace it with?
