### ISSUE TITLE
Extra path ?

### ISSUE THREAD

**Issue by spitters** [HoTT/book#867]
p_* should not be there in the second display on p146 of [the book](http://hottheory.files.wordpress.com/2013/03/hott-online-611-ga1a258c.pdf), or am I missing something. It does not seem to type check.

If you agree, I'll send a pull request.

**Comment by mikeshulman** [comment]
I think this was fixed in 2c194835?

**Comment by spitters** [comment]
Thanks! I knew that the book was automatically updated, but apparently under "nightly builds".
