### ISSUE TITLE
A theorem proves contractibility by showing ∑a, Π x (x = a) instead of the other direction.

### ISSUE THREAD

**Issue by 11Kilobytes** [HoTT/book#868]
Lemma 7.3.1 in the nightly version, which shows that the n-trunctation || A ||n is an n-type proceeds by showing that for all b : || A ||n, the type Map\*(S^(n + 1), (|| A ||n, b)) is contractible.  To show this, the proof constructs c(b) : Map\*(S^(n + 1), (|| A ||n, b)) and shows that for every other r, there is a path r = c(b).  However, in the HoTT book contractibility is defined the other way around, so we need to show c(b) = r instead. For clarity, I think it would be best to rewrite the proof to construct a path in the opposite direction.

**Comment by mikeshulman** [comment]
I think that by chapter 7 we can expect the reader to know that equality is
symmetric.

**Comment by 11Kilobytes** [comment]
I agree. However, the fractions of seconds the reader may spend thinking, "oh I can prove c(b) = r instead since equality is symmetric," are unnecessary IMO.

**Comment by mikeshulman** [comment]
I would say that the goal is to get to the point where that thought doesn't need to occur at all (thus taking zero time), and if the reader is still at the point where they have to have that thought, then it's good to force them to have it occasionally, so as to make progress towards the goal.

**Comment by 11Kilobytes** [comment]
Ahh, k. I withdraw my objection.
