### ISSUE TITLE
Make it more clear that univalence axiom is not  "(A=B) ~ (A~B)"

### ISSUE THREAD

**Issue by louisGarde** [HoTT/book#869]
The univalence axiom 2.10.3 is given with a sentence in two parts:
- the first part gives you the axiom, informally. It is of course precise and correct, but you need to stop your reading for a while and come back to 2.10.2 to really understand what the axiom is.
- the second part gives you the consequence "(A=B) ~ (A~B)", a short formula, self-standing, easy to understand and remember, and highlighted in the text (surrounded with empty lines and centered).

With a first quick reading, it is likely that you misunderstand the sentence and believe that the highlighted formula is the axiom. It happened to me, and certainly also to the author of the wikipedia definition of univalence.

I suggest that the consequence is clearly separated from the axiom, and stated just after as a Corollary.

**Comment by awodey** [comment]
Together with the sentence specifying which map is under consideration, the displayed type is a proposition which the axiom asserts is inhabited.

**Comment by mikeshulman** [comment]
I think he has a reasonable point; it's potentially confusing for the "conventional way of expressing" the axiom to be stated as _part_ of the axiom.
