### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by joliss** [HoTT/book#872]
The current release seems to be over a year old (from [March 6, 2014](https://hottheory.files.wordpress.com/2013/03/errata-611-ga1a258c.pdf)). Is there anything stopping us from turning the [current nightly](https://github.com/HoTT/book/wiki/Nightly-Builds) into a new release?

I'd particularly like to order a hardcopy of the current nightly. Also, there's no reason to point people to a year-old PDF if the new one is better.

**Comment by andrejbauer** [comment]
We're just lazy. We update the printed version every once in a while. I could do it again.

**Comment by mikeshulman** [comment]
Every time this comes up, I think "oh, I should do that", but then I wish that someone would get around to pulling #762 first, because I would hate to update with a version that I know still contains a mathematical error.  Of course that's not rational since the alternative is leaving the current version un-updated which contains that same error, but eh...

**Comment by EgbertRijke** [comment]
I'll have a look at the pull request.

2015-11-28 16:59 GMT-05:00 Mike Shulman <notifications@github.com>:

**Comment by EgbertRijke** [comment]
This might be a good moment to prepare a new release. There are no more pull requests open (other than the microtype request).

**Comment by mikeshulman** [comment]
Yep.  I was planning to do it today, but didn't have a chance. Maybe I'll
get to it next week, if someone else doesn't beat me to it.

**Comment by andrejbauer** [comment]
I got the technical problem with lulu.com resolved (the paperback was stuck, unable to change). I lowered the price of paperback to $13.45 (it was higher than hardback). I'll update, just let me know when 's a good moment. The dimensions of the cover need to be changed as the book grew significantly.

**Comment by mikeshulman** [comment]
Now is a good moment. Thanks!

**Comment by awodey** [comment]
great — thanks for doing this!
Steve

**Comment by joliss** [comment]
Ping :)

I'm going on a work-vacation in 2 weeks to read the book cover-to-cover. I have the nightly on my iPad, but would *love* to order a hardcopy to take with me, so I can read it in the sun.

**Comment by mikeshulman** [comment]
I've updated the "released" versions on the book web site, at long last, to point directly to the nightly builds (via saunders).  I don't have time to do lulu right now....

**Comment by andrejbauer** [comment]
I updated the lulu.com printed book versions with `first-edition-1005-ge9c58d7`. The prices went down;

* [paperback](http://www.lulu.com/shop/univalent-foundations-project/homotopy-type-theory-paperback/paperback/product-22480750.html) costs $9.73
* [hardback](http://www.lulu.com/shop/univalent-foundations-project/homotopy-type-theory-hardcover/hardcover/product-22480762.html) costs $22.05

I need to run, if someone can update the prices on the book home page that would be great. Also, if someone buys these, I would like a confirmation that they look ok.

**Comment by mikeshulman** [comment]
prices updated.  (Actually only the paperback version went down; the hardback version went up.)

**Comment by EgbertRijke** [comment]
I just ordered a copy, I didn't own one yet. It will arrive by Christmas.

2015-12-10 13:54 GMT-05:00 Mike Shulman <notifications@github.com>:

**Comment by joliss** [comment]
Yayyy, thanks for updating. And more importantly thanks for all the work that went into this. I've only read the first 30-odd pages, but I'm loving it already! 😃
