### ISSUE TITLE
correction to reference

### ISSUE THREAD

**Issue by RobertHarper** [HoTT/book#881]
Giovanni Sambin wrote to me to report that the monograph "Intuitionistic Type Theory" by Per Martin-Loef is improperly cited in the book.  The correct citation is (from him):

Per Martin-Löf, Intuitionistic Type Theory. Notes by Giovanni Sambin of a Series of Lectures given in Padua, June 1980, Bibliopolis, Napoli, 1984

Please correct this.  He is finding that others are copying it from the book, and he wishes to have it cited properly as being by Martin-Loef alone.

**Comment by mikeshulman** [comment]
I'm confused.  The current citation is

Per Martin-Lof. _Intuitionistic type theory_, volume 1 of _Studies in Proof Theory_. Bibliopolis, 1984.

This seems fairly clear to me that it is by Martin-Loef alone.  Is it that Sambin _wants_ to be mentioned as the notetaker?  I see that the bibtex has `Subtitle = {Notes by Giovanni Sambin},` but apparently the bib style didn't include that in the output; I guess we could move it into the Title field to make it display.

**Comment by RobertHarper** [comment]
i sent the citation that he wants.

bob

**Comment by mikeshulman** [comment]
Ok, so you are saying that what he wants is to be mentioned as the notetaker.  That makes perfect sense to me; I was just confused by your last sentence since it implied to me that what he wanted was *not* to be cited as a coauthor.
