### ISSUE TITLE
axioms, rules, canonicity

### ISSUE THREAD

**Issue by louisGarde** [HoTT/book#885]
At the end of chapter 1.1 it is stated that "(../..) the type theory presented in this chapter (../..) consists entirely of rules, without any axioms".
This is in contradiction with the explanations following in the same paragraph, for instance "the rules are the rules of the game, while the axioms are the starting position".
That implies that HoTT (without univalence) is a formal game without starting position !

From my point of view, the meaning of "axiom" when saying "the type theory has no axiom" can only be defined from the concept of canonicity: an "axiom" is then is a rule that breaks the canonicity property. What is the state-of-the-art definition of an axiom in type theory ?

I would suggest to clearly define the canonicity property, as for instance it is done in nLab, and to clarify the definition of "axiom" - either as the leaves of the proof trees, or the rules that break canonicity..

**Comment by mikeshulman** [comment]
> That implies that HoTT (without univalence) is a formal game without starting position!

Not exactly; it implies that it is a formal game whose starting position is empty.  Plenty of games start on an empty board, like Go.

You're right, though, that the meaning of "axiom" in type theory is a bit unclear.  One definition might be that an axiom is simply a hypothesis added to the context in which the rest of the theory is developed.  Another might be that it's a premise-free rule whose conclusion is a term judgment.

**Comment by mikeshulman** [comment]
Looking back at the wording here, I think we are pretty clear: we do say explicitly that "the axioms are the judgments we are given at the outset", and discuss canonicity in a later paragraph.
