### ISSUE TITLE
Topological example in 1.12.1 goes into the margin.

### ISSUE THREAD

**Issue by MrChico** [HoTT/book#892]
In the book version `first-edition-1005-ge9c58d7` I have, the definition of the punctured disc in the end of 1.12.1 bleeds into the margin of the page and is not completely visible.

**Comment by andrejbauer** [comment]
Which book format? (use letter, us trade?) Is it the printed book?

**Comment by MrChico** [comment]
Printed, paperback copy

**Comment by andrejbauer** [comment]
Yeah, we still have some of those left over. Thanks for reporting.

**Comment by jkingdon** [comment]
This problem is still present in hott-ebook-1075-g3c53219.pdf (in that case, page 68).

**Comment by mikeshulman** [comment]
Hmm, I think this is the same problem from #930, which was fixed in 0141610790, but for some reason the posted builds have not updated for a while.

**Comment by mikeshulman** [comment]
I'm going to close this issue, the real problem is #950 .
