### ISSUE TITLE
The book bugs on TeX Live 2016

### ISSUE THREAD

**Issue by EgbertRijke** [HoTT/book#898]
When compiling the book with TeX Live 2016, I get the following error:

    ! LaTeX Error: No counter 'r' defined.
    
    See the LaTeX manual or LaTeX Companion for explanation.
    Type  H <return>  for immediate help.
     ...                                              
                                                      
    l.547 \begin{rmk}
                     \label{rmk:introducing-new-concepts}
    ?

It compiles fine with TeX Live 2015. According to [this answer](http://tex.stackexchange.com/a/316037/14653) on tex.stackexchange, the problem could be fixed by including in ``macros.tex`` the lines

    \let\xx@thm\@thm
    \AtBeginDocument{\let\@thm\xx@thm}

directly after 

    \newtheorem{thm}{Theorem}[section]
    \crefname{thm}{Theorem}{Theorems}

This works. However, I'm quite sceptical of whether this is a stable fix. So I just report the problem.

**Comment by EgbertRijke** [comment]
Probably the best thing to do for the time being, is to warn users to not use TL2016 to compile the book, because it seems that the bug is introduced in hyperref of TL2016. It is not really a bug in the book, I think.

**Comment by mikeshulman** [comment]
I agree, it doesn't look like a bug in the book.  But does the hacky fix break anything else?  If not, I don't see any harm in including it, with a comment about its purpose and that it can be removed once hyperref/TL2016 is updated.

**Comment by EgbertRijke** [comment]
I had email contact with the author of hyperref, @davidcarlisle. To try, he sent me a fixed version of hyperref, with which the book compiles normally. He says he will upload it to CTAN in the weekend. 

So I suspect it is not worth putting the hack in the book.

**Comment by mikeshulman** [comment]
Is there a prospect of actually updating TeXLive 2016, or will its users have to manually download an updated version of hyperref?

**Comment by davidcarlisle** [comment]
it normally goes from ctan to texlive within a day, so tlmgr update should
install it in a day or so (I plan to push to ctan now, just finalising the
packaging)

On 24 June 2016 at 23:00, Mike Shulman <notifications@github.com> wrote:

> Is there a prospect of actually updating TeXLive 2016, or will its users
> have to manually download an updated version of hyperref?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/HoTT/book/issues/898#issuecomment-228472662>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABNcAqwOqst1kzAgwSv6aRFiLWNl0Xcoks5qPFN5gaJpZM4I8uEO>
> .
>



-- 
http://dpcarlisle.blogspot.com/

**Comment by mikeshulman** [comment]
Nice, thanks!  So we can probably close this issue.
