### ISSUE TITLE
Missing proof obligation in Corollary 7.7.3 (Reflective subuniverse preserves products)

### ISSUE THREAD

**Issue by dlicata335** [HoTT/book#901]
A question came up at LICS to which the answer was essentially "not not - is a reflective subuniverse", but in the process of working through this, I noticed what I think is a problem with 7.7.3.  

I think there's a missing proof obligation here: to show that O(AxB) = OA x OB, you need to show that OA x OB **is in U_P,** admits a map from A x B (which is given later in the text), and that composition with that map is an equivalence, right?  I.e. the lemma on this line:
https://github.com/dlicata335/hott-agda/blob/master/misc/Reflective.agda#L81

What's written here confused me, because without the obligation to show that the "candidate O" is in U_P, the same argument that's given here works to show that A+B is in U_P if A and B are, which isn't true:
https://github.com/dlicata335/hott-agda/blob/master/misc/Reflective.agda#L119

Originally I thought that 7.7.3 was used to _prove_ that AxB is in U_P if A and B are, but this can be done directly by essentially the same argument for Pi:
https://github.com/dlicata335/hott-agda/blob/master/misc/Reflective.agda#L47
This works for Pi and \* because you can work on the right before peeling off the O on the left, and this is the part that fails for coproducts.  

Does this seem right?

**Comment by mikeshulman** [comment]
I agree that you have to know that OA x OB is in U_P for this argument to work.  That should certainly be stated more clearly in the proof, but I think that *technically* it's not missing because the fourth bullet after Definition 7.7.1 says "The types in U_P are closed under all limits such as products and pullbacks."  (-:
