### ISSUE TITLE
Different arrows: confusion

### ISSUE THREAD

**Issue by petercommand** [HoTT/book#903]
In lemma 2.3.1,
transport^P(P,-) is introduced as a function P(x) -> P(y)
However, in theorem 3.2.2, there is a use of transport : transport^(A |-> (\neg \neg A -> A))
What is the definition of this different kind of arrow |-> (with a little vertical bar on the left) ? Is it defined anywhere in the book?

**Comment by petercommand** [comment]
I think it just means pi type, but this is not mentioned anywhere in the book

**Comment by mikeshulman** [comment]
It's a notation for lambda-abstraction.  Page 22.

**Comment by petercommand** [comment]
But in page 22, the arrow |-> is not used

**Comment by mikeshulman** [comment]
Sorry, I shouldn't use page numbers since there are different versions; I mean section 1.2.  It's in the displayed equation introduced with "Another equivalent notation is".

**Comment by petercommand** [comment]
OK, I see
