### ISSUE TITLE
what does the book mean by "making the latter more explicit" in section '6.5 Suspensions' ?

### ISSUE THREAD

**Issue by xieyuheng** [HoTT/book#905]
----------------

in section '6.5 Suspensions'

----------------

there is a definition :
    S^0 :≡ 2
    S^(n+1) :≡ ΣS^n

and it says :
"To prove carefully that this agrees with the definition of S^n from the previous section would require making the latter more explicit."

what does the book mean by "making the latter more explicit" ?

----------------

and we have :
Lemma 6.5.1. Σ2 = S^1.

I tried to mimic the proof and to prove ΣΣ2 = S^2 directly

I find I have difficulty proving it,
because of there are no 1-loops other then refl(base) in S^2.

how would you prove ΣΣ2 = S^2 directly ?

----------------

**Comment by mikeshulman** [comment]
"Making the latter more explicit" is a reference to the last paragraph of section 6.4:

> In order to write down the induction principle for this presentation, we would need to define
a notion of “dependent n-loop”, along with the action of dependent functions on n-loops.

You can do it for S^2 without this, indeed it's exercise 6.2.  I don't want to deprive you of the fun of doing that exercise, but the basic idea is to use the recursion principles to give maps in both directions, then the induction principles to prove their composites are equal to identities, just as in Lemma 6.5.1.

**Comment by xieyuheng** [comment]
thanks for your reply mikeshulman

but 'Exercise 6.2' is to prove ΣS^1 = S^2,
that would be different from proving ΣΣ2 = S^2 directly right ?

I think I can solve 'Exercise 6.2',
but when it comes 'to prove ΣΣ2 = S^2 directly',
the mothed I used to solve 'Exercise 6.2' no longer applies.

I have tried many hours on ΣΣ2 = S^2,
it must be something wrong with the way I use the mothed.

It would be very kind of you, if you could give it a try.
(and to guide me back to the right track >_<)

**Comment by mikeshulman** [comment]
Well, given Lemma 6.5.1 and the fact that suspension preserves equivalence (which is trivial if we use univalence), the two statements are equivalent.  But you can also prove the other one directly and the basic method is the same.  You just have to use the recursion/induction principles for *both* of the suspensions in ΣΣ2, i.e. use the induction principle for the outer one, then in the two resulting clauses use the induction principle for the inner one.

**Comment by xieyuheng** [comment]
----------------

to prove ΣΣ2 and S^2 are of the same homotopy type

----------------

    S^2 defined as
    B : S^2
    surf : refl(B) = refl(B)

----------------

    Σ2 defined as
    n : Σ2
    s : Σ2
    m(1) : n = s
    m(2) : n = s
     
    ΣΣ2 defined as
    N : ΣΣ2
    S : ΣΣ2
    M(n) : N = S
    M(s) : N = S

----------------

suppose I choose the following f and g

----------------

    f : (ΣΣ2 -> S^2)
    f(N) = B
    f(S) = B
     
    : (Σ2 -> B = B)
    f(n) = refl(B)
    f(s) = refl(B)
     
    : (n = s -> refl(B) = refl(B))
    f(m(0)) = surf
    f(m(1)) = refl(refl(B))

----------------

    g : (S^2 -> ΣΣ2)
    g(B) = N
     
    : (refl(B) = refl(B) -> refl(N) = refl(N))
    g(surf) = M(m(0)) * (M(m(1)))^{-1}

----------------

I found it is impossible to prove the composition g◦f : (ΣΣ2 -> ΣΣ2)
is equal to identity function of ΣΣ2

----------------

Am I choosing the right f and g ?

how would you prove the composition g◦f : (ΣΣ2 -> ΣΣ2)
is equal to identity function of ΣΣ2 ?

If you think I am choosing the right f and g,
could you try to concretely prove it this time ?
(just like how the proof in 'Lemma 6.5.1' goes)

----------------

**Comment by mikeshulman** [comment]
Your definitions look reasonable.  I don't have time to write out the proof myself right now, but I would do it as I said, by using the induction principle of ΣΣ2.  Have you tried using a proof assistant to help generate all the cases?

**Comment by xieyuheng** [comment]
----------------

I have not yet tried to use agda to generate all the cases, nor coq to direct the proof.

but the following is my arguments about why
"it is impossible to prove the composition g◦f : (ΣΣ2 -> ΣΣ2)
is equal to identity function of ΣΣ2"

(while I know my method fails to prove "ΣΣ2 and S^2 are of the same homotopy type",
so it is highly likely there are mistakes within my arguments,
I hope you could spot my mistakes. (when you have time, of course))

----------------

I think the function body of g◦f is the following

----------------

    g◦f : (ΣΣ2 -> ΣΣ2)
    g◦f(N) = B
    g◦f(S) = B

    : (Σ2 -> N = N)
    g◦f(n) = refl(N)
    g◦f(s) = refl(N)

    : (n = s -> refl(N) = refl(N))
    g◦f(m(0)) = M(m(0)) * (M(m(1)))^{-1}
    g◦f(m(1)) = refl(refl(N))

----------------

to prove g◦f is equal to identity function of ΣΣ2,
I tried to find a function of type ((x : ΣΣ2) -> g(f(x)) = x)

----------------

   k : ((x : ΣΣ2) -> g(f(x)) = x)
   suppose
   k(N) = p1 : (N = N)
   k(S) = p2 : (N = S)

----------------

transport the fibration ((x : ΣΣ2) -> g(f(x)) = x)
I think we will get two equations about p1 and p2,
one from M(n), another from M(s)
(i.e. two equations in the groupoid of paths in ΣΣ2)

----------------

    g◦f(n)^{-1} · p1 · M(n) == p2
    g◦f(s)^{-1} · p1 · M(s) == p2

    i.e.
    refl(N)^{-1} · p1 · M(n) == p2
    refl(N)^{-1} · p1 · M(s) == p2

    i.e.
    p1 · M(n) == p2
    p1 · M(s) == p2

    we get
    p1 · M(n) == p1 · M(s)

    we get
    M(n) == M(s)

----------------

I do not think the equations are solvable,
for it implys  M(n) == M(s)  in the groupoid.

thus "it is impossible to prove the composition g◦f : (ΣΣ2 -> ΣΣ2)
is equal to identity function of ΣΣ2".

----------------

**Comment by mikeshulman** [comment]
I suggest trying Agda or Coq; they'll be able to find any mistakes much faster than I could.  (-:

**Comment by xieyuheng** [comment]
I am closing this issue now, my friends,
because I think that I've figured out the matter about my equations.

they are actually solvable,
because M(n) is transportationally equal to M(s).

sorry to bug you,
and thanks again for your precious time.
