### ISSUE TITLE
Ambiguous variable bindings in Exercise 10.13

### ISSUE THREAD

**Issue by koba-e964** [HoTT/book#910]
The formula
```
∀(x ∈ V).∀(y ∈ x).∃(z ∈ V).z ∈ y ⇒ ∃(c ∈ (∪x)^x).∀(y ∈ x).c(y) ∈ y
```
in Exercise 10.13 is ambiguous. I think the leftmost `∀(x ∈ V)` quantifies the entire formula, and the other quantifiers work as usual. Is it correct?
If it is correct, how about changing it to
```
∀(x ∈ V).[∀(y ∈ x).∃(z ∈ V).z ∈ y ⇒ ∃(c ∈ (∪x)^x).∀(y ∈ x).c(y) ∈ y]
```
(adding brackets)?

**Comment by mikeshulman** [comment]
In chapter 1 we said that all binding operators like lambda, Pi, and Sigma scope over the entire expression unless delimited by parentheses.  We didn't explicitly mention this when introducing ∃ and ∀, but I would expect it to apply to them too.  So I would say it should be instead

    ∀(x ∈ V).(∀(y ∈ x).∃(z ∈ V).z ∈ y) ⇒ ∃(c ∈ (∪x)^x).∀(y ∈ x).c(y) ∈ y

**Comment by koba-e964** [comment]
I see. I will make a pull request later. Does it need an erratum?

**Comment by mikeshulman** [comment]
I would say yes, since as written it is actually incorrect under any possible convention.

It wouldn't be wrong to add extra parentheses around the whole expression for clarity:

    ∀(x ∈ V).((∀(y ∈ x).∃(z ∈ V).z ∈ y) ⇒ ∃(c ∈ (∪x)^x).∀(y ∈ x).c(y) ∈ y)

Maybe make the outer ones `\Big` to set them apart.  If you think that would help, feel free to do it too.
