### ISSUE TITLE
Notation `v ∈ V` in Section 10.5

### ISSUE THREAD

**Issue by koba-e964** [HoTT/book#912]
In the definition of `V`-set, the notation `v ∈ V` is not defined yet. Although it is obvious that it means `v : V`, it would be helpful to add some notes.

**Comment by andrejbauer** [comment]
Can you point to a specific example (please refer by numbering of sections and theorems, not page numbers)? The memership relation `v ∈ V` is specifically discussed and defined in 10.5, between equations (10.5.2) and (10.5.3). It is *not* the same thing as `v : V`.

**Comment by mikeshulman** [comment]
It took me a while too, but I think the OP is referring to [this line](https://github.com/HoTT/book/blob/master/setmath.tex#L1532), which I think actually is a typo and should be `v:V`.

**Comment by koba-e964** [comment]
The notation `∈ V` appears 3 times. I was referring to https://github.com/HoTT/book/blob/cfecd410c6b4dbf62e4ebf481d76726de09d9d20/setmath.tex#L1532 and https://github.com/HoTT/book/blob/cfecd410c6b4dbf62e4ebf481d76726de09d9d20/setmath.tex#L1917 . I think that fixing them as typos and/or defining new notation `∈ V` is ok.

**Comment by mikeshulman** [comment]
Thanks!  I think the others are typos too, and now that that is pointed out, `\fall{y\in x}` should really be `\fall{y:V} (y\in x) \to`, unless we want to define the former as an abbreviation for the latter.

**Comment by koba-e964** [comment]
Thanks! I see.
About `∈ V`, I think simply replacing them with `: V` would work. About `\fall{y \in x}`, I think a brief definition of this notation would be better than replacing them with `\fall{y: V} (y \in x) \to`, because of the convenience of this notation.
Any ideas?

**Comment by mikeshulman** [comment]
If we were going to use it a lot, I would say we should define it, but if this is the only occurrence of it in the book, I doubt it is worth it to define.

**Comment by koba-e964** [comment]
The notation `\fall{y \in x}` was defined as _bounded_ quantifiers before and in the proof of Corollary 10.5.9.

**Comment by mikeshulman** [comment]
Ah, I suppose it is.
