### ISSUE TITLE
\choice{\infty,\infty} in Exercise 7.8

### ISSUE THREAD

**Issue by koba-e964** [HoTT/book#915]
`\choice{\infty,\infty}` is
```
\prd{X:\set}{Y:X\to\UU}
  \Parens{\prd{x:X} Y(x)}
  \to
  \prd{x:X} Y(x)
```
, which is obvious by `\idfunc[\prd{x:X} Y(x)]` and not Theorem 2.15.7.

**Comment by ljustice6** [comment]
What is this about

**Comment by mikeshulman** [comment]
Right you are.  Care to submit a pull request?

**Comment by koba-e964** [comment]
Sure. I made a pull request.
