### ISSUE TITLE
Section numbers missing

### ISSUE THREAD

**Issue by mikeshulman** [HoTT/book#923]
When I compile the book on my personal computer, none of the section headings include numbers.  The numbers are still there on the [nightly build](https://hott.github.io/book/nightly/hott-online-1075-g3c53219.pdf), so maybe I have a different version of some LaTeX package?  Anyone have any idea what could be going on?  I recently got a new computer, so I don't know whether this was introduced by a change to the book or by a change to my computer.

**Comment by peterlefanulumsdaine** [comment]
Fixed in c35b67d.
