### ISSUE TITLE
How to cite bibliography entries from errata list?

### ISSUE THREAD

**Issue by peterlefanulumsdaine** [HoTT/book#928]
In case we ever want to cite bibliography items in the errata list, it’s not clear to me how to do so.  The `xcite` package seems to provide exactly what we want — allowing one file to cite items from the bibliography generated by another file; see 66aa5c5 for an attempt to use this in our case.  However, this produces (for me) an `Undefined Control Sequence` error (I guess from an interaction between `xcite` and something else in our setup) — although despite this error, the compiled pdf is fine and contains the citation as desired.

(Also as per #927, it’s not clear whether the erratum in 66aa5c5 really needs to be added anyway.)

**Comment by mikeshulman** [comment]
Why exactly would we want to use `xcite` rather than simply giving the errata file its own bibliography?

**Comment by mikeshulman** [comment]
Also, how can I `checkout` 66aa5c5 to try it?  Just doing `git checkout 66aa5c5` (after `git pull upstream master`) "does not match any file(s) known to git".  Is it on a branch?

**Comment by JasonGross** [comment]
Rather than `git pull upstream master`, try `git remote update`.  Does that work?

**Comment by mikeshulman** [comment]
Nope.

**Comment by peterlefanulumsdaine** [comment]
The commit is on my fork, so I think `git remote add pll https://github.com/peterlefanulumsdaine/HoTT.git`, followed by `git checkout errata-xcite` or `git checkout 66aa5c5` should work?

**Comment by mikeshulman** [comment]
Thanks, that works!  (The edited version, anyway.  (-: )

**Comment by mikeshulman** [comment]
Well, I don't know what the problem with xcite is, but since we're already rolling our own solution for cross-references instead of using `xr`, we might as well do the same thing for bibliographic entries: 0042a53c20 (in my fork, branch `errata-xcite` rebased from yours)

**Comment by mikeshulman** [comment]
Since #927 was merged without an erratum, I'm going to close this issue.
