### ISSUE TITLE
Formal type theory : Dependent function types

### ISSUE THREAD

**Issue by varunp94** [HoTT/book#929]
Hi,

In section A.2.4 which states the rules of inference for dependent function types, the Pi-UNIQ rule derives the judgmental equality between f and (\lambda)x.f(x). As per my current understanding, in order to do this, we first need to derive the judgment 'the term (\lambda)x.f(x) is of type (\Pi)(x:A)B'. How do we do that?

We would require the judgment " (\Gamma), x:A |- f(x): B " as the hypothesis of the Pi-INTRO rule. However, this judgment does not seem to follow from the Pi-ELIM rule (which defines f(x)) using any of the previously stated structural rules. 

In fact, if you state this as the elimination rule i.e., given the hypothesis "(\Gamma) |- f : (\Pi)(x:A)B" we can infer " (\Gamma), x:A |- f(x): B ", then the current Pi-ELIM seems to be derivable by using substitution rules.

I am also facing similar problems in other type formers. For example, in dependent pair types, in Sigma-ELIM, we write g : C[(x,y)/z], but I am not able to derive (x,y):(\Sigma)(x:A)B from Sigma-INTRO. Could you kindly help me solve this?

Thanks,
Varun.

**Comment by SkySkimmer** [comment]
> As per my current understanding, in order to do this, we first need to derive the judgment 'the term (\lambda)x.f(x) is of type (\Pi)(x:A)B'

It's more that we need to ensure it is derivable in order to avoid strangeness.

If `ctx |- f : \Pi x : A, B` is derivable then `ctx |- \lambda x, f x : \Pi x : A, B` is derivable like this https://i.imgur.com/ZsCDbGv.png
The `ctx |- f : \Pi ...` `=>` `ctx, x : A |- f : \Pi ...` is called Wkg1 (weakening) in the book. It's not an actual rule, it's a statement that if we have a derivation of the top bit we can get a derivation of the bottom bit.
In the same way, we also know that a derivation of `ctx |- f : \Pi x : A, B` implies a derivation of `ctx, x : A is a context`.

Does this help?

**Comment by varunp94** [comment]
> It's more that we need to ensure it is derivable in order to avoid strangeness.

Isn't it necessary to have a rule which states that the judgment 'a is definitionally equal to b of type A in a context `ctx`' is well-formed only when we have the judgments `ctx |- a : A` and `ctx |- b : A`? Has it been shown that permitting such 'strangeness' won't lead to undesirable consequences (by which I mean that we'll be able to derive undesirable judgments like inhabiting the empty type)? 

> If ctx |- f : \Pi x : A, B is derivable then ctx |- \lambda x, f x : \Pi x : A, B is derivable like this https://i.imgur.com/ZsCDbGv.png
The ctx |- f : \Pi ... => ctx, x : A |- f : \Pi ... is called Wkg1 (weakening) in the book.

I think in the weakening rule Wkg 1, when the additional judgment `x : A` is added to the context of the judgment `\Gamma, \Delta |- b : B` to form the judgment `\Gamma, x : A, \Delta |- b : B`, it is implicitly assumed that the variable 'x' is distinct from all the other variables that appear in the hypothesis of the inference rule.  The application of weakening here seems to be a classic case of variable capture (in this case, of the free variable x by the operator \Pi) and therefore, the derivation is invalid.

**Comment by SkySkimmer** [comment]
> Isn't it necessary to have a rule which states that the judgment 'a is definitionally equal to b of type A in a context ctx' is well-formed only when we have the judgments ctx |- a : A and ctx |- b : A?

To be sane the theory must ensure that if `ctx |- e = f : A` is derivable then `ctx |- e : A` and `ctx |- f : A` are derivable. An insane theory might or might not inhabit the empty type depending on the theory.
(eg a theory which has only a rule `[] |- lambda x y : Type, x = lambda x y : Type, y` and no typing rules fails the above condition but inhabits no types)
Maybe I shouldn't have used the word 'strangeness'. I definitely agree that it's a desirable property.

>I think in the weakening rule Wkg 1, when the additional judgment x : A is added to the context of the judgment \Gamma, \Delta |- b : B to form the judgment \Gamma, x : A, \Delta |- b : B, it is implicitly assumed that the variable 'x' is distinct from all the other variables that appear in the hypothesis of the inference rule. The application of weakening here seems to be a classic case of variable capture (in this case, of the free variable x by the operator \Pi) and therefore, the derivation is invalid.

There is no free variable `x` in the judgement `\Gamma |- f : \Pi_{(x : A)} B`. If you prefer every time I wrote `\Pi_{(x : A)} B` you can see it as `\Pi_{(y : A)} B[y/x]` for some fresh `y`. So the `x` which gets added to the context is intended to be shadowed by the one in the Pi binder and there is no capture.

**Comment by mikeshulman** [comment]
I'm certainly not an expert here, but my current understanding is that often there is a choice about how to present a type theory, whether (for instance) `ctx |- e  : A` and `ctx |- f : A` must be known to be derivable *before* you are allowed to consider `ctx |- e = f : A`, or whether instead the derivability of `ctx |- e = f : A` *ensures* (as a metatheorem) that  `ctx |- e  : A` and `ctx |- f : A` are also derivable.  There's some relation with positivity/negativity of type formers and/or analyticitc/syntheticity of judgments that suggests which choice is more appropriate.  But a real type theorist like @dlicata335, who explained this to me once, would be able to say it better.

**Comment by varunp94** [comment]
> There is no free variable x in the judgement \Gamma |- f : \Pi_{(x : A)} B. If you prefer every time I wrote \Pi_{(x : A)} B you can see it as \Pi_{(y : A)} B[y/x] for some fresh y.

In that case we would derive the judgment `\Gamma, x : A |- f(x) : B[y/x]` after applying Pi-ELIM in the above derivation. Is this the same as the judgment `\Gamma, x : A |- f(x) : B`? They are obviously different syntactically.

**Comment by SkySkimmer** [comment]
You get `\Gamma, x : A |- f(x) : (B[y/x])[x/y]` (ie replace x by y, then replace y by x), and `(B[y/x])[x/y]` is exactly `B` syntactically.

**Comment by varunp94** [comment]
> You get \Gamma, x : A |- f(x) : (B[y/x])[x/y] (ie replace x by y, then replace y by x), and (B[y/x])[x/y] is exactly B syntactically.

I am sorry, but I am not able to understand this. How is `(B[y/x])[x/y]` exactly `B` syntactically? Could you kindly guide me to a reference which derives the substitution and weakening rules?

**Comment by mikeshulman** [comment]
Technically, `(B[y/x])[x/y]` is only identical to `B` if `B` doesn't contain `y` to start with, but that's the case here.  Isn't it intuitively obvious that if you substitute `y` for all occurrences of `x`, then substitute `x` for all occurrences of `y`, you get back to where you started?  `x^2+1` becomes `y^2+1` and then `x^2+1` again.

**Comment by varunp94** [comment]
> Isn't it intuitively obvious that if you substitute y for all occurrences of x, then substitute x for all occurrences of y, you get back to where you started? x^2+1 becomes y^2+1 and then x^2+1 again.

But, we were talking about whether they are _syntactically_ the same. Interpreting `B[y/x]` as 'substituting `y` for all free occurrences of `x` in `B`' is just our understanding of the formal object `B[y/x]` (or more precisely it is the translation of the formal type theory into English). 

So, another way of framing the question I asked before is that what are the necessary and sufficient rules in formal type theory concerning substitution such that the formal object `B[y/x]` 'behaves' exactly like how we interpret it in English?

**Comment by SkySkimmer** [comment]
`B[a/x]` is (very quickly) defined at the beginning of the appendix, just before A.1. It's a meta-level definition, not a part of the syntax. So for instance `x[a/y]` is the term `x`, and `(f x)[a/x]` is the term `f a` (if `f` does not contain `x`).
In the same way with universes when it says `U_i : U_{i+1}` the `i+1` is the meta level addition, or with contexts `\Gamma, \Delta` is the list concatenation.

If we were defining the theory in Coq, we would say something like
```
Inductive term :=
| Universe (i : nat)
| Var (x : var)
| Pi (x : var) (a : term) (b : term)
| Lambda (x : var) (a : term) (b : term)
| Apply (f : term) (e : term).
(* possibly more stuff, eg sigma types *)

(* subst e x v = e[v/x] *)
Fixpoint subst e x v :=
match e with
| Universe i => Universe i
| Var y => if x =? y then v else Var y
| ... => ... (* not writing the rest because it has annoying stuff to avoid capture *)
end.

Lemma subst_back_and_forth e x y : not (In y (freevars e)) -> subst (subst e x (Var y)) y (Var x) = e.
Proof. ... Qed.

Definition context := list (var * term).
Inductive valid_context : context Prop := ...
with is_type : context -> term -> Prop := ...
with has_type : context -> term -> term -> Prop := ...

Theorem weakening : forall ctx e t, has_type ctx e t -> forall x a, not (In x (ctx_domain ctx)) -> is_type ctx a -> has_type ((x,a)::ctx) e t.
Proof. ... Qed.
(* etc *)
```
Also `subst_back_and_forth` is a definitional identity on ground terms (no Coq variables).

Other presentations have substitutions as objects in the syntax (explicit substitutions), and then they have to have rules involving it for the conversion like `(f e)[a/x] == f[a/x] (e[a/x])` etc. Just not either of the presentations in the book.

**Comment by mikeshulman** [comment]
Closing this old issue; if there is still something to discuss feel free to reopen.
