### ISSUE TITLE
typos in proof of 7.3.12, and other comments about that proof

### ISSUE THREAD

**Issue by jdchristensen** [HoTT/book#940]
In the proof of Theorem 7.3.12:

In the paragraph showing that decode(encode(p)) = p, the two occurrences of "encode" in the prose should be "decode".  These are:

"what we need to know is that encode(r(u)) = refl_u"

and

"it follows by definition of r and encode".

In the last displayed equation of the proof, with five equalities, the type family in the middle line should be changed from "v \mapsto ||u=v||_n" to "y \mapsto ||x=y||_n".

In would also be kind to the reader to change the period at the end of the display to a comma and add "using Lemmas 2.3.10 and 2.3.11."  Or, the proof can be simplified by doing induction on p, in which case the second line computes to the correct answer.  (This is how the HoTT library does it.)

A final comment is that twice in the prose it says that the goal is an n-type and therefore an (n+1)-type, but in both cases the goal is in fact an (n-1)-type, if I'm not mistaken.  I think it would be more clear if "n" were changed to "n-1" in both places.

**Comment by mikeshulman** [comment]
I think that the fourth line in the five-equality proof also should refer to x and y instead of u and v, right?  I made that change too.

**Comment by jdchristensen** [comment]
I agree that the fourth line should change as well.  But in both the third and fourth lines, I think it should be "y \mapsto" not "x \mapsto".
