### ISSUE TITLE
Ill-typed equality in 6.7,  last bullet point

### ISSUE THREAD

**Issue by marcbezem** [HoTT/book#942]
The equality reads:

apd_g(loop) = p'.q'.(p')^-1.(q')^-1, 

where the composition is between dependent paths (pathovers). (This composition is left to the reader 
in Section 6.6, after the last bullet point.)

We have the following typings:

apd_g(loop) : (transport (P o f) loop b') = b', where b' == g base : P b, == definitional equality,

p'.q'.(p')^-1.(q')^-1 : (transport P f(loop) b') = b'.

Now, (transport (P o f) loop b') and (transport P f(loop) b') are not definitionally equal but only propositionally. This means that the two terms left of the : cannot be directly equated, but with a little transport we can fix this. We do perhaps not want too many details here, so I propose this formulation:

"apd_g(loop) = t (p'.q'.(p')^-1.(q')^-1), with composition of dependent paths and t a suitable transport function."

Marc

**Comment by mikeshulman** [comment]
You're right.  I would be a little more explicit than that, see my proposed fix.

**Comment by marcbezem** [comment]
Excellent fix, thanks!

**Comment by mikeshulman** [comment]
Thanks.  Don't close the issue until the pull request is merged, though.
