### ISSUE TITLE
Confusing Notation in Section 1.6

### ISSUE THREAD

**Issue by jtmayer** [HoTT/book#943]
On page 43,
![hott-1 6-confusing-notation](https://user-images.githubusercontent.com/9361227/30523423-dc97490a-9b95-11e7-8f48-3b5ef0ac6829.png)

It might not be obvious to some readers that f is being obtained by application of a function. That is, it is not completely clear that the lambda expression that takes x is being applied to the lambda expression that takes f.

**Comment by telephon** [comment]
Also the `x` in the expression on the right (the function that is passed to the lambda-expression) and the `x` in the lambda-expression are (should be?) different x.

**Comment by jtmayer** [comment]
It shouldn't matter, because the x for the lambda expression is completely encapsulated by the lambda expression itself, but it might also be a good idea to clarify this as well.

**Comment by telephon** [comment]
Yes, exactly: in the α-conversion, the one `x` is replaced by some other letter. But for readers unfamiliar with this rule, it might be a little misleading.

**Comment by mikeshulman** [comment]
Regarding the first point, the lambda expression that takes *f* is being applied to the lambda expression that takes *x*, not the other way around.  I don't see any sense in which *f* is being "obtained".  Can you make a more specific suggestion?

As for the second point, I don't think any &alpha;-conversion is needed.  The &beta;-reduction produces

```
\Pi_{(x:A)} R(x,(\lambda x. pr_1(g(x)))(x))
```

in which the `x` in `g(x)` is bound by `\lambda x` (shadowing the outer `x`).  Then a further &beta;-reduction substitutes the outer `x` for the inner `x`, producing

```
\Pi_{(x:A)} R(x,pr_1(g(x)))
```

as desired.  I can see that one might argue it would be clearer to use a different variable name to avoid shadowing, but I think there's another argument that it's actually clearer this way, because ultimately both `x`s do get identified.

**Comment by awodey** [comment]
I actually think it’s fine as is.

**Comment by jtmayer** [comment]
@mikeshulman The problem is a single syntax is being used to describe two separate semantics without explicitly saying so. In the first lambda expression, parenthesis are used to denote operational precedence, but for the second lambda expression, parenthesis are used to denote a parameter to a function.

**Comment by mikeshulman** [comment]
Why is that a problem?  Parentheses are used in both of those ways all throughout mathematics.

**Comment by jtmayer** [comment]
The math is not wrong, it is purely an issue of clarity. As someone who is trying to communicate an idea, you should not assume the reader will understand what you are trying to do just because the notation is correct.

**Comment by mikeshulman** [comment]
I repeat, can you make a more specific *suggestion*?  What would you change?  I can't think of any other way to notate this.

**Comment by jtmayer** [comment]
Well, I would suggest either defining the first lambda expression as named function, or state in words that the second lambda expression is a argument to the first lambda expression.

**Comment by mikeshulman** [comment]
Your first comment said "It might not be obvious to some readers".  Taken literally this sounds like just speculation.  Do you know of at least one reader to whom it was definitely not obvious, i.e. was someone *actually* confused by this, or are you just speculating?

**Comment by jtmayer** [comment]
Yes, that reader would be myself. When I figured it out, I asked myself why the author would write it in such a way.

**Comment by mikeshulman** [comment]
If "I asked myself why the author would write it in such a way" is meant as a question, then I would say the answer is that that's the straightforward way to write it; in fact I don't think there's any *other* way to write it short of (as you suggested) introducing a nonce definition, which I would find ugly (and potentially more confusing in other ways).  However, given evidence that at least one person was actually confused, I'd be happy to insert a clarifying parenthetical to help future readers become used to this sort of notation.  Thanks for bringing it up!
