### ISSUE TITLE
Syntax rule for dependent function types

### ISSUE THREAD

**Issue by AxelBoldt** [HoTT/book#948]
Section 1.4 contains the sentence "Like λ-abstractions, Πs automatically scope over the rest of
the expression unless delimited", but it should occur earlier, since the issue already arises three paragraphs earlier, in the discussion of the polymorphic identity function.

**Comment by andrejbauer** [comment]
Should this have been closed by @mikeshulman commit above?

**Comment by mikeshulman** [comment]
Someone needs to merge #951 first.
