### ISSUE TITLE
Update "in preparation" references?

### ISSUE THREAD

**Issue by 1-p** [HoTT/book#957]
There are two "in preparation" reference by a quick search, namely

> [LS13b] Peter LeFanu Lumsdaine and Michael Shulman. Higher inductive types. In preparation, 2013. (Cited on pages 11, 175, 218, and 440.)

> [MvdB13] Ieke Moerdijk and Benno van den Berg. W-types in cartesian model categories. in preparation, 2013. (Cited on page 175.)

Have those papers appeared already or replaced by some other papers?

**Comment by mikeshulman** [comment]
Good point!  The first is https://arxiv.org/abs/1705.07088.  I'm not positive about the second, but maybe it is https://arxiv.org/abs/1307.2765; in any case that is closely related and a reasonable paper to cite there.
