### ISSUE TITLE
Gap in proof of Lemma 3.8.2

### ISSUE THREAD

**Issue by martinescardo** [HoTT/book#964]
We set Y(x) = Sigma(a:A(x)), P(x,a). But we forget to argue that Y(x) is a set. One proof is that sets are closed under Sigma, and propositions are sets. Another one is that, because P(x,a) is a proposition, the projection pr1 : Y(x) -> A(x) is an embedding, and any type embedded into a set is itself a set. it suffices that the map be left-cancellable - so we can use Lemma 3.5.1 for this part. However, I don't think the machinery to give a complete argument is in place when Lemma 3.8.2 is proved. We could give a forward reference, because choice is not used except in a few isolated places in the book (like ordinals).

**Comment by mikeshulman** [comment]
Example 3.1.5 says that sets are closed under Sigma, and Lemma 3.3.4 says that propositions are sets.  What is missing?

**Comment by martinescardo** [comment]
(For some reason, I missed a notification about your reply.)

Ah, good. What is missing is to mention that 3.1.5 and 3.3.4 need to be applied, and why. I came across this when I was formalizing in Agda something that required this, where it became clear that these two additional things need to be proved but are not mentioned in the proof in the book.

**Comment by mikeshulman** [comment]
Good point; see #984.
