### ISSUE TITLE
Translation to Spanish

### ISSUE THREAD

**Issue by Santu41** [HoTT/book#969]
I would like to contribute to your project by translating into Spanish if there is any content that needs that kind of work... :+1:

**Comment by mikeshulman** [comment]
Feel free!

**Comment by dbucci24** [comment]
hey @mikeshulman I will also contribute in the translation! 😄

**Comment by andrejbauer** [comment]
It's going to be a bit difficult to translate the whole book. I see you already started translating the "Reading HoTT in Coq". Another possibility is to translate some other introduction to HoTT into Spanish (not the book). For example the introduction that @DanGrayson wrote.

**Comment by dbucci24** [comment]
@andrejbauer What is the name of that introduction?

**Comment by dbucci24** [comment]
I can translate the book too :)

**Comment by mikeshulman** [comment]
By the way, while I am all in favor of translating things, as I said on the other thread, my first reaction is that such translations should be in a fork or a separate project.

**Comment by DanGrayson** [comment]
You can see my introduction at https://arxiv.org/abs/1711.01477

**Comment by mikeshulman** [comment]
As discussed at #971, @dbucci24 has started a fork for such a translation.
