### ISSUE TITLE
A suggestion of an exercise about split monomorphisms

### ISSUE THREAD

**Issue by koba-e964** [HoTT/book#999]
I believe that the following are logically equivalent:
(a) LEM,
(b) for every sets A and B, if A is inhabited then for every monomorphism f: A -> B, f is also a split monomorphism. (i.e. f has a retraction.)
(a) -> (b) can be proved just like in classical set theory. (b) -> (a) can be proved by considering a monomorphism f: 1 + P -> 2 (`f(inl(*)) \defeq 0, f(inr(_)) \defeq 1`) for a mere proposition P. If we pick a retraction g of f, checking if `g(1) = inl(*)` decides whether P holds.
How about adding this as an exercise? If this is added, I think appending it to the last of Exercise 10 is good.

**Comment by mikeshulman** [comment]
That sounds good to me.  Yes, new exercises should be appended to the list of exercises, and Chapter 10 seems a reasonable place (although Chapter 3 might also be).
